### ISSUE TITLE
Inquire how to load 100 million data into one collection

### ISSUE THREAD

**Issue by hyunmokky** [qdrant/qdrant-client#111]
### **Versions**
qdrant_client version: 1.0.0
python: 3.9

### **Summary**
Hello, there was a timeout error while loading the data into the collection. I'm going to load about 100 million data per collection. I want to know which function of qdrant client should be used to load 100 million data. Also, 100 million data can be loaded into one collection, right? Also, how much minimum storage capacity should be in order to load 100 million data into qdrant?

**Comment by monatis** [comment]
hi @hyunmokky, there's no hard limit on the number of vectors you can upload to one collection, so yes, you can, considering the following:

- Before uploading, set `indexing_threshold` to a very large number to disable indexing temporarily. You can set it a reasonable value again after the upload is complete.
- Make sure that you have enough storage. The amount of storage required is heavily dependent on the vector dimension, amount of payload data if any, and HNSW params you choose. Be aware that 1Kb = 1 vector of size 256.
- You can use either `.upload_records()` or `.upload_collection()` methods for parallel uploading, depending on which one suits better on the rest of your code, e.g., whether you produce vectors and/or payload data one by one or as a large Numpy array, for example.
