### ISSUE TITLE
Safer collection creation

### ISSUE THREAD

**Issue by Mikkolehtimaki** [qdrant/qdrant-client#113]
I have a use case where I dynamically need to create collections rather often, and then insert into existing collections.

Perhaps I missed but it seems that the client is missing a convenience method to create a collection only if it does not exist. If I recreate I seem to lose previously uploaded vectors. My options are

1. call `client.get_collections` and iterate over to check if the name is there
2. call `client.get_collection(name)` and check if that fails

Somehow both seem a bit risky, e.g. they may fail for reasons that are independent of the collection already existing. So could there be a safer way to create a collection _if it does not already exist_?

**Comment by monatis** [comment]
Hi @Mikkolehtimaki,`relying on the failure of `.get_collection()` may be risky as failure can also happen due to a network issue, but why do you think it's risky to get a list with `.get_collections()` and check it?

I agree with the necessity of a convenience method, though. For example, `.create_collection(..., exist_ok: bool)`

**Comment by Mikkolehtimaki** [comment]
For `get_collections` I was thinking of a case where I have parallel requests coming in to upload data to the same new collection. Both will first check the collection names and get a list without the collection there, so both could try to recreate it. And the second recreation may happen after the first one has uploaded data, causing data loss. Is this a valid concern?

**Comment by monatis** [comment]
I suggest that you separate the collection creation logic from data uploading. You can check the existence of the collection at app startup and create it if it does not exist. Then it can wait for new data to upload. In this case, parallel uploads should work without any trouble as the collection has been created at startup. You can implement it with `.get_collections()`, but I'll also implement the convenience method directly in the client package.

**Comment by Mikkolehtimaki** [comment]
Yeah that is my current method. Basically separate API calls to initialize collections and to upload data. I'd love this to be transparent to the user though, so that's where the convenience method can help. Thanks!

**Comment by joein** [comment]
Hi @Mikkolehtimaki 

Now we have `create_collection` method, can I close the issue?

**Comment by Mikkolehtimaki** [comment]
Yeah that seems to work as expected! Documentation is still referring to recreate_collection.
