### ISSUE TITLE
Inquire for Python version extensions where qdrant-client is available.

### ISSUE THREAD

**Issue by hyunmokky** [qdrant/qdrant-client#129]
### Versions
python: 3.6.9

### Summary
Qdrant is an attractive search engine. Through the qdrant-client library, users use the various features of qdrant. However, the qdrant-client is only available with Python versions 3.7 and later. Our Python version is 3.6.9. The qdrant-client is currently not available in the 3.6.9 Python version. We currently configure all systems with version 3.6.9 of Python.

I want to know how to use the qdrant-client in Python version 3.6.9.

**Comment by generall** [comment]
python 3.6 is at the end-of-life https://devguide.python.org/versions/ and is not supported anymore. Please consider updating
