### ISSUE TITLE
Warning on deletion of the grpc connection

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-client#132]
> from Dicsord: https://discord.com/channels/877056448956346408/1082984155547193385/1085888420221558784

Hi ⚫qdrant team, just found a little Warning message using qdrant_client to connect to the cloud. All ois working properly on localhost, but when i try to connect to my cluster online, i got the warning message below.

The code before which threw the error:
print("Entry")
qdrant_client = QdrantClient(
    url=os.environ.get("QDRANT_URL"), 
    prefer_grpc=True,
    api_key=os.environ.get("QDRANT_API_TOKEN"),
)
print("End")

The error:
![image](https://user-images.githubusercontent.com/1935623/225630173-705aaf78-73e7-44b6-ab13-de5e7fe71288.png)

But when I delete myself the qdrant_client, it work properly.
print("Entry")
qdrant_client = QdrantClient(
    url=os.environ.get("QDRANT_URL"), 
    prefer_grpc=True,
    api_key=os.environ.get("QDRANT_API_TOKEN"),
)
del qdrant_client
print("End")

**Comment by joein** [comment]
I tried to reproduce it on python 3.9 and 3.10 with `qdrant-client==1.1.0`

I used
1) existing standalone qdrant instance in the cloud with 2m vectors of dim 384 (not free tier)
2) a new and empty instance of a standalone qdrant instance in the cloud (free tier)
3) a new cluster of 3 nodes in the cloud, I've also tried to upload some data and then close channel

But I couldn't reproduce it

**Comment by joein** [comment]
I think there might be a network issue/server side problem => connection being dropped on another end and we can't properly close grpc channel on client side
