### ISSUE TITLE
size mismatch between vector and indexed vector 

### ISSUE THREAD

**Issue by anandhperumal** [qdrant/qdrant-client#135]
I have inserted into qdrant server with the help of qdrant client around 0.7M records.
I see there is a mismatch between the indexed_vector_count and vectors_count. 
Why is this happening? Also my indexing_threshold is set to 10000 and my vector dimension is set 768, so the indexed_vectors_count should be 0, right?

`{'status': <CollectionStatus.GREEN: 'green'>, 'optimizer_status': <OptimizersStatusOneOf.OK: 'ok'>, 'vectors_count': 727462, 'indexed_vectors_count': 715228, 'points_count': 727462, 'segments_count': 8, 'config': {'params': {'vectors': {'size': 768, 'distance': <Distance.COSINE: 'Cosine'>}, 'shard_number': 1, 'replication_factor': 1, 'write_consistency_factor': 1, 'on_disk_payload': True}, 'hnsw_config': {'m': 16, 'ef_construct': 100, 'full_scan_threshold': 10000, 'max_indexing_threads': 0, 'on_disk': False, 'payload_m': None}, 'optimizer_config': {'deleted_threshold': 0.2, 'vacuum_min_vector_number': 1000, 'default_segment_number': 0, 'max_segment_size': None, 'memmap_threshold': None, 'indexing_threshold': 20000, 'flush_interval_sec': 5, 'max_optimization_threads': 1}, 'wal_config': {'wal_capacity_mb': 32, 'wal_segments_ahead': 0}}, 'payload_schema': {}}`

**Comment by generall** [comment]
Hi @anandhperumal! Qdrant split collection into segments and indexes only those segments which are large enough. If segment is small, it is not that efficient to build vector index, as full-scan will work faster. Please consider `indexed_vectors_count` simply as indication that index works and covers majority of points.

Worth mentioning, that even if point is not marked as indexed, it is still available in search and any other API.

**Comment by anandhperumal** [comment]
@generall that’s what even my understanding was from the document but all my vectors is of same size 768, so ideally they indexed_vector and vector_count should match, isn’t it?

**Comment by generall** [comment]
vector size doesn't affect this. Indexing is defined by the number of vectors in the segment. And apparently you have one small segment which was not indexed
