### ISSUE TITLE
client.upsert() race condition issue

### ISSUE THREAD

**Issue by zmtbnv** [qdrant/qdrant-client#146]
Hi team,

How does QDrant handle [race condition](https://en.wikipedia.org/wiki/Race_condition) while uploading vectors in parallel in real time applications?

**Example:**
There are 4 realtime **applications (A, B, C, D)** uploading different payloads at different times to Qdrant collection using `client.set_payload()` method. At the same time, there is one **application (E)** uploading vectors realtime to the same collection. 

Since uploads by all applications are happening in real time, there is high chance that the Point with vector doesn't exists when **A, B, C** or **D** tries to `set_payload`. Thus, they first check if Point exists with `client.retrieve()` and if the Point doesn't they will create placeholder vector with `[0.0] * vector_dim`  using `client.upsert() or client.upload_collection()` methods to be able to set  the payload. This placeholder vector will be replaced by **application E** when it does `upsert` real vector. However, there is also a chance that **application E** may upload vectors ahead of **A, B, C, D**, which leads to situation when **A,B,C,D** overwrite actual vector with placeholder containing `[0.0]` values.

Because, `client.upsert()` and `client.upload_collection()` both overwrite existing vector, I'm wondering if there is any way to make sure that **A, B, C, D** do not overwrite actual vector with placeholder one if `E` runs milli/microsecond ahead of them? Possible solution could be `create`, instead of `upsert`.

Illustration (time flows left to right):
```bash
App A: client.retrieve(ids=[1]) -----> [] ------> client.upsert(id=1, vector=[0.0, 0.0]) --> client.set_payload(id=1, payload={'a': 1})
                               App E: client.upsert(id=1, vector=[0.82, 0.31])
````
which results in `placeholder vector [0.0, 0.0]` instead of actual one `[0.82, 0.31]` due to fraction of a second difference between **A** and **E** 

Thanks in advance.

**Comment by joein** [comment]
Going to close due to inactivity
