### ISSUE TITLE
How to get a list of all collections in my cluster? 

### ISSUE THREAD

**Issue by mzhadigerov** [qdrant/qdrant-client#147]
I designed a webapp so that users set a name for the collection themself. I treat a collection name as a name of a document they upload.

Since I don't know the names of the collections they input, I am wondering how can I get the names of the collections available in my cluster?

**Comment by kacperlukawski** [comment]
@mzhadigerov You can always list the collections: https://qdrant.github.io/qdrant/redoc/index.html#tag/collections/operation/get_collections

**Comment by mzhadigerov** [comment]
Thanks @kacperlukawski !
