### ISSUE TITLE
get_collection not working for local mode 

### ISSUE THREAD

**Issue by gd1m3y** [qdrant/qdrant-client#149]
Hey 
So i have tried setting up qdrant client for local mode and created a single collection but when i hit the get_collections method i get the following error 
```
rest_models.CollectionDescription(collection_name=name)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CollectionDescription
name
  field required (type=value_error.missing)
  ```
The method get_collection() works . 
python version 3.9.15

**Comment by generall** [comment]
Hi @gd1m3y, thanks for reporting!

**Comment by generall** [comment]
Please try `qdrant-client==1.1.3`

**Comment by gd1m3y** [comment]
Just Checked method get_collections() working on local mode now 
Thankyou for your quick response 
Closing the issue :-)
