### ISSUE TITLE
Error in uploading large embeddings

### ISSUE THREAD

**Issue by balakreshnan** [qdrant/qdrant-client#161]
I have a dataframe with 9400 rows with embeddings and i an chunking as 50 per push in for loop and getting this error:
{"status":{"error":"Wrong input: Missed vector name error: "},"time":0.004534833}

if i try to upload the entire things local machine memory goes to 50GB and nothing is getting inserted into qdrant server.

any help pls.

**Comment by generall** [comment]
Hi @balakreshnan, could you please describe exact steps to reproduce the issue?

**Comment by balakreshnan** [comment]
I have a data frame with content column and enbedding column, token various from 50 to 500 per row,
I have converted to embedding ada2 model
then my goal is to save to content and embedding in 50 rows at a time chunk

code sample -
import numpy as np
from qdrant_client.models import PointStruct
import time

for i in range(start, len(df2), chunksize) :
    #display(df1.iloc[i:chunksize])
    df3 = pd.DataFrame()
    df3 = df2.iloc[int(i):int(chunksize + i)].copy()
    print(str(i) + " " + str(len(df3)))
    try:
        #processdf(client, df3)
        client.upsert(
        collection_name="ciodeveloperindex",
        points=[
            PointStruct(
                id=idx,
                vector=vector,
                paylod = { "name": df3["content"] }
            )
            for idx, vector in enumerate(df3["embedding"])
            ]
        )
    except Exception as e:
        print("An exception occurred", e)
        continue;
    #time.sleep(3)
    i = i + chunksize

thanks
Bala
________________________________

**Comment by joein** [comment]
Hi, @balakreshnan 

We may also need code with which you created your collection

P.S. If you copy-pasted this code, then there is  also a typo in `PointStruct`. It should be `payload`, not `paylod`

**Comment by balakreshnan** [comment]
i corrected the payload and same error:

Collection is just simple load a json file with content into dataframe and create embeddings

df['embedding'] = ''

for i in range(len(df)):
#for i in range(760,765):
    try:
        embedding = openai.Embedding.create(input=df['content'][i], deployment_id="text-embedding-ada-002")
        df['embedding'][i] = embedding['data'][0]['embedding']
    except Exception as err:
        i
        print(f"Unexpected {err=}, {type(err)=}")

thanks
bala
________________________________

**Comment by balakreshnan** [comment]
also you should know this first 50 rows gets updated after than all errors


An exception occurred Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Missed vector name error: "},"time":0.0157648}'
50 50
An exception occurred Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Missed vector name error: "},"time":0.008319753}'


thanks
Bala
________________________________

**Comment by joein** [comment]
> We may also need code with which you created your collection

I mean `QdrantClient.create_collection` or `QdrantClient.recreate_collection` invocation, could you show it?

**Comment by joein** [comment]
@balakreshnan does this problem still occur for you?
