### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by answerMA** [qdrant/qdrant-client#178]
First initialize the instance of qdrant client, and then call any method in the instance at random, like get_collections or search, and the error will appear randomly, and the probability of occurrence is not low. There will definitely be 1-2 failures out of 5 calls.

There is no firewall configuration for port 6333. At the same time, it is still in the development stage, and only I will use qdrant server, and there will be no high concurrency.

`qdrant_client = QdrantClient(url,prefer_grpc=False, timeout=500)`
the url string exclude 'http' schema

qdrant server stays with default configs

qdrant imgae: latest
qdrant client:1.2.0

does any one knows how to fix this or change any cinfigs to avoid http connections reset errors ? 

![image](https://github.com/qdrant/qdrant-client/assets/3457139/c786f7e4-b637-486b-8005-6752a5d887b1)

When this error occurs, there is no error message in the server log

![image](https://github.com/qdrant/qdrant-client/assets/3457139/1e0eb354-a9aa-4fa9-81c1-2a25c6e35e94)

**Comment by generall** [comment]
did you solve it?

**Comment by gulldan** [comment]
how you solve it?
