### ISSUE TITLE
[BUG] `search_groups` errors when query_vector is numpy array, works with `.tolist()`

### ISSUE THREAD

**Issue by jturner116** [qdrant/qdrant-client#188]
```Python
client.search_groups(
    collection_name='wiki_search',
    query_vector=qv, #Numpy array
    group_by='article_id',
    limit=4,
    group_size=2
)
```
returns the following errors in jsonable_encoder
`ValueError: [TypeError('cannot convert dictionary update sequence element #0 to a sequence'), TypeError('vars() argument must have __dict__ attribute')]`

Sending query_vector to a Python list resolves the issue, but numpy arrays should be supported [here](https://github.com/qdrant/qdrant-client/blob/0d3448c9af3c431eb9dd275fe83c2ba67a17ee46/qdrant_client/client_base.py#L40) ?
Thanks!

**Comment by joein** [comment]
Hi, thanks for reporting

#190

**Comment by jturner116** [comment]
Fixed with that PR, thanks!
