### ISSUE TITLE
[BUG] Qdrant python client doesn't return vector even with with_vector option set

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [qdrant/qdrant-client#189]

**Comment by suryaa62** [comment]
`import qdrant_client
from qdrant_client.http import models

client = qdrant_client.QdrantClient("localhost", port=6333)

client.recreate_collection(
    collection_name="test",
    vectors_config=models.VectorParams(size=3, distance=models.Distance.COSINE),
)

client.upsert(collection_name="test" , points= [ models.PointStruct(
	id = 2,
	payload = {
		"document_id" : "1234",
	},

	vector=[0.9 , 0.1 , 0.3],
) ] )

record = client.retrieve(collection_name="test" , ids=[2] , with_vector=True)

print(record)`

**Comment by suryaa62** [comment]
How to reproduce error:

```python
import qdrant_client
from qdrant_client.http import models

client = qdrant_client.QdrantClient("localhost", port=6333)

client.recreate_collection(
    collection_name="test",
    vectors_config=models.VectorParams(size=3, distance=models.Distance.COSINE),
)

client.upsert(collection_name="test" , points= [ models.PointStruct(
	id = 2,
	payload = {
		"document_id" : "1234",
	},

	vector=[0.9 , 0.1 , 0.3],
) ] )

record = client.retrieve(collection_name="test" , ids=[2] , with_vector=True)

print(record)
``` 

Output: [Record(id=2, payload={'document_id': '1234'}, vector=None)]

**Comment by suryaa62** [comment]
if I use the rest api to get the same point, I get the vector in the response

**Comment by joein** [comment]
Hi, it is `with_vectors`, not `with_vector`, additional assert statements will be introduced in the next release to avoid such situations

**Comment by dhruv-anand-aintech** [comment]
thanks for the clarification
