### ISSUE TITLE
Correct way to Disable Logging?

### ISSUE THREAD

**Issue by AlbinoGeek** [qdrant/qdrant-client#197]
Hey there!

Is there a way to disable console logging (such as on document insert) in the Python client?

I have tried setting environment variables or passing arguments to the `qdrant_client`.

```env
QDRANT__DEBUG=0
QDRANT__LOG_LEVEL=WARN # ERR WARNING ERROR etc etc attempted
```

They appear to have no effect, I still see stdout when working with a local database.

```python
qdrant_client = QdrantClient(
    location=":memory:",
)
```

**Comment by joein** [comment]
@AlbinoGeek sorry for the delay,
you can just do 

```python
import logging

logger = logging.getLogger()
logger.setLevel(logging.ERROR)
```

to avoid warnings in qdrant local mode

**Comment by joein** [comment]
Feel free to reopen the issue if it is still relevant

**Comment by matteosdocsity** [comment]
@joein how to disable qdrant info logging only? but not touching any other qdrant info
