### ISSUE TITLE
Python dedicated documentation

### ISSUE THREAD

**Issue by JeyDi** [qdrant/qdrant-client#198]
Hi guys! I really like Qdrant and I'm using on daily basics, I wonder if it's possible to start building a dedicated python documentation using mkdocs for example.
I can help on that and start working on the first implementation following the Redoc and Qdrant official documentation.
What do you think? Someone already built something?
Thank you!

**Comment by davidmyriel** [comment]
@JeyDi thanks for pointing this out. New documentation is coming. I will share an mvp version here.

**Comment by JeyDi** [comment]
I'll be glad to help you guys on the documentation if necessary :)

**Comment by joein** [comment]
There is [python dedicated documentation](https://python-client.qdrant.tech/quickstart)

It's work in progress though and will be improved later

Closing this issue for now in favour of more precise issues like #355 #354 #348
