### ISSUE TITLE
with_vectors search mismatch

### ISSUE THREAD

**Issue by davidmyriel** [qdrant/qdrant-client#219]
Please take a look at the following thread: https://discord.com/channels/907569970500743200/1128952656212267038

A user was unable to get the vectors back when I query, but they did get the payload back on v.1.3.1.

As per @joein:

______________________
The documentation is correct, I believe

search method uses with_vectors, while SearchRequest  is awaiting with_vector, we probably need to fix this in the client
______________________

**Comment by joein** [comment]
we decided to start with restricting extra fields in the models so the users could have a proper error message if they try to set incorrect field #222
