### ISSUE TITLE
Issue Getting Payload with Async grpc.SearchPoints

### ISSUE THREAD

**Issue by alinneman** [qdrant/qdrant-client#225]
Hello, 

I'm trying to get a handle on the async functionality of the Qdrant client. I created a quick script based off of your [example](https://github.com/qdrant/qdrant-client/blob/730ed8d239d79bc1adec0d7c2efc31b63be9b8e5/tests/test_async_qdrant_client.py) that works as expected:

```Python
import asyncio
import numpy as np
from qdrant_client import QdrantClient, models, grpc

# Function to perform a single query
async def perform_query(client, query_vector):
    result = await client.Search(grpc.SearchPoints(vector=query_vector, collection_name='test_collection', limit=20))
    return result

# Function to run multiple queries concurrently using asyncio.gather()
async def run_queries():
    client = QdrantClient('some_host', grpc_port=6334, prefer_grpc=True).async_grpc_points

    queries = [np.random.rand(1115).tolist() for _ in range(10)]

    # Create a list of coroutines for each query
    query_coroutines = [perform_query(client, query_vector) for query_vector in queries]

    # Use asyncio.gather() to execute all coroutines concurrently
    results = await asyncio.gather(*query_coroutines)
    return results

# Create and run the event loop manually
loop = asyncio.new_event_loop()
results = loop.run_until_complete(run_queries())
loop.close()

# Print the results
for idx, result in enumerate(results):
    print(f"Result for query {idx + 1}: {result}")
```

But now I want the search to return the payload. So I added the `with_payload=True` arg to `grpc.SearchPoints()` like so:

```Python
async def perform_query(client, query_vector):
    result = await client.Search(grpc.SearchPoints(vector=query_vector, collection_name='test_collection', limit=20, with_payload=True))
    return result
```

Doing so results in the following error:
```
TypeError: Message must be initialized with a dict: qdrant.SearchPoints
```

As far as I can tell that error message seems to come from Google protobuf (assuming because of gRPC), but I can't seem to see much further than that. 

My versions of qdrant and protobuf (latest stable as of now):
```
protobuf==4.23.4
qdrant-client==1.3.1
```

Am I going about accessing the payload incorrectly here?

**Comment by joein** [comment]
Hello @alinneman 

`with_payload` does not accept just bools, instead it accepts `grpc.WithPayloadSelector` structure.

protobuf structures are generated via proto files
They can be found in [this dir](https://github.com/qdrant/qdrant-client/tree/730ed8d239d79bc1adec0d7c2efc31b63be9b8e5/qdrant_client/proto)

[grpc.SearchPoints](https://github.com/qdrant/qdrant-client/blob/730ed8d239d79bc1adec0d7c2efc31b63be9b8e5/qdrant_client/proto/points.proto#L222C1-L235C1)

[grpc.WithPayloadSelector](https://github.com/qdrant/qdrant-client/blob/730ed8d239d79bc1adec0d7c2efc31b63be9b8e5/qdrant_client/proto/points.proto#L151C1-L157C2)

```python
grpc.SearchPoints(
    vector=query_vector, 
    collection_name='test_collection',
    limit=20, 
    with_payload=grpc.WithPayloadSelector(enable=True)
)
```

**Comment by alinneman** [comment]
Ahh that's a big help, thanks! I know you guys have docs in the works, so I just need to learn how to crawl the repo in the meantime 😊
