### ISSUE TITLE
Cant recreate collection

### ISSUE THREAD

**Issue by zinoubm** [qdrant/qdrant-client#234]
When trying to recreate a collection 

`client = QdrantClient(url="****", api_key=****)
client.recreate_collection(
    collection_name="my_collection",
    vectors_config=models.VectorParams(size=100, distance=models.Distance.COSINE),
)`

I got the following error:

 [/usr/local/lib/python3.10/dist-packages/qdrant_client/http/api_client.py](https://localhost:8080/#) in send(self, request, type_)
     89             except ValidationError as e:
     90                 raise ResponseHandlingException(e)
---> 91         raise UnexpectedResponse.for_response(response)
     92 
     93     def send_inner(self, request: Request) -> Response:

UnexpectedResponse: Unexpected Response: 415 (Unsupported Media Type)
Raw response content:
b'{"result":null,"status":{"error":"Content type error"},"time":0.0}

**Comment by joein** [comment]
hello @zinoubm 

which version of qdrant-client do you use?
and where do you host qdrant instance?
do you use qdrant cloud?

**Comment by zinoubm** [comment]
I'm using client with version `1.3.2` and Qdrant-cloud

**Comment by joein** [comment]
Thanks, I will check it out

**Comment by zinoubm** [comment]
Thanks, I appreciate It.

**Comment by zinoubm** [comment]
I just solved the problem by Updating my Qdrant-cloud Instance from the UI, It was running on an old version. I switched  it to `1.3.2`

**Comment by joein** [comment]
Which version was it?

**Comment by zinoubm** [comment]
I can't see, the Qdrant-cloud UI dropdown is disabled now.

**Comment by joein** [comment]
Ok

**Comment by joein** [comment]
I was able to reproduce it with `qdrant-client==1.3.2`, `qdrant v1.1.0`, however these versions should not be used together.
But still, there was a bug in client, thanks for creating an issue :)

#235
