### ISSUE TITLE
deleting points does not prune sqlite db file in local mode

### ISSUE THREAD

**Issue by sidhujag** [qdrant/qdrant-client#239]
I noticed that the sqlite file in local mode doesn't shrink after deleting points from qdrant local setup (Isn't it supposed to?)

In python:
1) Setting up client
```
collection_name='test_collection'
client = QdrantClient(path=path)
client.create_collection(
                on_disk_payload=True,
                collection_name=collection_name,
                vectors_config=rest.VectorParams(
                    size = 1536,
                    distance = rest.Distance.COSINE,
                ),
            )
client.create_payload_index(collection_name, 'metadata.conversation, field_schema=PayloadSchemaType.KEYWORD)
# make some pushes to collection with conversation=2...
...
```

2) Setup filter qdrant_filter=(should=None must=[FieldCondition(key='metadata.conversation', match=MatchValue(value='2'), range=None, geo_bounding_box=None, geo_radius=None, values_count=None)] must_not=None)

`client.delete(collection_name='test_collection', points_selector=qdrant_filter, wait = True)`

3) Result: operation_id=0 status=<UpdateStatus.COMPLETED: 'completed'>

4) In my storage.sqlite file I noticed it was accessed and changed but the data must have not been removed because as I added vectors and payloads it increased by multiple kilobytes and I removed the same collection via conversation filter and the file didn't go back to the original size. I can confirm the points are not found after delete but the filesize remains unchanged.

**Comment by AhmedHemeedi** [comment]
Yes, you are correct. The sqlite file in local mode should shrink after deleting points from Qdrant local setup.
The reason why the file is not shrinking is because Qdrant does not currently support point deletion in local mode. This is a known issue and is being tracked by the Qdrant team.
In the meantime, there are a few workarounds that you can use to shrink the sqlite file:

You can delete the entire collection and recreate it. This will remove all of the points from the collection, including the deleted points.

You can use the qdrant vacuum command to remove unused data from the sqlite file. This will not remove the deleted points, but it will free up some space in the file.

**Comment by sidhujag** [comment]
> ```python
> client.execute_sql(collection_name='test_collection', sql_query='VACUUM;')
> ```

This function does not exist in qdrant client anywhere, where did you get this information?

https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/local/qdrant_local.py

**Comment by joein** [comment]
I am actually not sure whether we need to expose sql connections or vacuum query, since it is not supposed to use local mode with large amount of vectors and db size usually should not exceed 1-2GB (which I think everyone can afford)

**Comment by sidhujag** [comment]
for remote it makes sense once the application scales up, is there a way to get collections by paging? We use one collection per user with multiple indexes/filters inside so to work across all users (to prune or manage) we need a way to get collections in a way such that if there are billions of users theoretically we can run through them paged

**Comment by joein** [comment]
it is not usually recommended to have collection-per-user

have you taken a look at https://qdrant.tech/documentation/tutorials/multiple-partitions/#configure-multitenancy ?

answering your question - no, there is no paging in `get_collections`

**Comment by sidhujag** [comment]
> it is not usually recommended to have collection-per-user
> 
> have you taken a look at https://qdrant.tech/documentation/tutorials/multiple-partitions/#configure-multitenancy ?
> 
> answering your question - no, there is no paging in `get_collections`

thanks, is group_id automatically indexed or should we create this as a payload index?

**Comment by joein** [comment]
you should create it

**Comment by joein** [comment]
closing this for now, feel free to re-open/create new issue/ask questions in discord :)
