### ISSUE TITLE
Adding new embeddings to existed collection

### ISSUE THREAD

**Issue by UmarIgan** [qdrant/qdrant-client#248]
I see that there is way to add new embeddings to existing cluster that have embeddings via **insert** function, but in this function I couldn't understand the mentality. I uploaded my previous document with **update_vectors**  function and wondering what is the easiest way to add new embdeddings? In the following code:
1 - read a pandas dataframe that has text column
2 - connect and create collection from Qdrant
3 - upload first 100 records

when I  upload second 100 records, first 100 records dissapear which I believe this is what function does but is there way to upload new records to existing collection without changing encoder for a list of dataset?

```
from qdrant_client import models, QdrantClient
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer('all-MiniLM-L6-v2')


from qdrant_client import QdrantClient
qdrant_client = QdrantClient(
    url=''
    api_key=''
     )

qdrant_client.recreate_collection(
	collection_name="cluster_test",
	vectors_config=models.VectorParams(
		size=encoder.get_sentence_embedding_dimension(), # Vector size is defined by used model
		distance=models.Distance.COSINE
	)
)


qdrant_client.update_vectors(
	    collection_name="cluster_test",
	    records=[models.Record(
			id=idx,
			vectors=encoder.encode(doc["text"]).tolist(),#change it with your own dataset
			payload=doc
		) for idx, doc in enumerate(df[:100].to_dict(orient='records'))
])


```

**Comment by joein** [comment]
Hi @UmarIgan 

`update_vectors` is not a method to add new points, it behaves correspondingly to its name - updates vectors for already uploaded points - [link](https://qdrant.tech/documentation/concepts/points/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgzOm50aC1vZi10eXBlKDEp#update-vectors)

there are three methods to upload points
- [upsert](https://qdrant.tech/documentation/concepts/points/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgyOm50aC1vZi10eXBlKDMp#upload-points)
- [upload_collection](https://github.com/qdrant/qdrant-client/blob/cddf1c540741e15483cedaaa4e6c0cfbd8c57049/qdrant_client/qdrant_remote.py#L1946C22-L1946C22)
- [upload_records](https://github.com/qdrant/qdrant-client/blob/cddf1c540741e15483cedaaa4e6c0cfbd8c57049/qdrant_client/qdrant_remote.py#L1931)

The latter two methods have the same functionality, just different signature (you either provides vectors, ids and payload as separate arguments, or already created Records)

Please pay attention that you need to specify ids explicitly, if you want to have a possibility to upload new embeddings later
