### ISSUE TITLE
List IDs in Collection

### ISSUE THREAD

**Issue by TariqAHassan** [qdrant/qdrant-client#255]
Hello,

Perhaps I have missed this, but there is any way to list the IDs currently stored in a collection?

**Comment by generall** [comment]
Hi @TariqAHassan 

You can try Scroll Points API: https://qdrant.tech/documentation/concepts/points/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIGgyOm50aC1vZi10eXBlKDcp

It is possible to disable payloads and vectors, so it will only return IDs

**Comment by TariqAHassan** [comment]
That's exactly what I was looking for. :)

Thanks @generall.
