### ISSUE TITLE
No .add on method implemented on the client - the new method from the docs not working

### ISSUE THREAD

**Issue by grski** [qdrant/qdrant-client#269]
Step by step:
1. Installed qdrant-client and fastembed with 
```
poetry add fastembed qdrant-client
```
2. qdrant-client seems to be there and it seems like a new version (btw latest release on github is different than on pypi)
```
❯ python -m pip freeze | grep qdrant
qdrant-client==1.4.0
```
3. Then i go:
```
from qdrant_client import QdrantClient
client = QdrantClient(":memory:")
client.add(...)
```
4. In response i get an error:
```
Unresolved attribute reference 'add' for class 'QdrantClient'
```

I seem to have proper version:
```
Metadata-Version: 2.1
Name: qdrant-client
Version: 1.4.0
Summary: Client library for the Qdrant vector search engine
Home-page: https://github.com/qdrant/qdrant-client
License: Apache-2.0
```
Searched the QdrantBase class and QdrantClient in the package files for the add() method but it seems to not be there.

It might be some kind of dependency problem on my side, but doesn't seem like it.

Python: 3.11.3
OS: latest OS X, running Apple M1 chip 

Info about the package:
```
[[package]]
name = "qdrant-client"
version = "1.4.0"
description = "Client library for the Qdrant vector search engine"
optional = false
python-versions = ">=3.7,<3.12"
files = [
    {file = "qdrant_client-1.4.0-py3-none-any.whl", hash = "sha256:2f9e563955b5163da98016f2ed38d9aea5058576c7c5844e9aa205d28155f56d"},
    {file = "qdrant_client-1.4.0.tar.gz", hash = "sha256:2e54f5a80eb1e7e67f4603b76365af4817af15fb3d0c0f44de4fd93afbbe5537"},
]
```

Let me know if you could use some addiitonal info or any help.

**Comment by grski** [comment]
I checked against 3.11.4 same issue.
Then I went to https://pypi.org/project/qdrant-client/1.4.0/#files, manually downloaded the archive and it does seem different compared to the current state of the codebase.

So probably just a problem with the release.

**Comment by joein** [comment]
hey @grski, afaik we haven't yet officially announced this feature, will be available soon with the next client's release, as for now, you can use it from master branch

**Comment by grski** [comment]
@joein yup, `poetry add git+ssh://git@github.com:qdrant/qdrant-client.git` works, thanks!
