### ISSUE TITLE
AttributeError: 'QdrantClient' object has no attribute 'add'

### ISSUE THREAD

**Issue by phantomdenkali** [qdrant/qdrant-client#276]
using python client on windows, I am going through the documentation on the qdrant-client repo: https://github.com/qdrant/qdrant-client

The following line seems to fail:
```

# Use the new add method
client.add(collection_name="demo_collection", documents={"documents": docs, "metadatas": metadatas, "ids": ids})


```

Am I using some older version of the client?

here's the complete code. and the error:
```

    client.add(collection_name="demo_collection", documents={"documents": docs, "metadatas": metadatas, "ids": ids})
    ^^^^^^^^^^
AttributeError: 'QdrantClient' object has no attribute 'add'
```
```
import numpy as np
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct, Filter, FieldCondition, Range



client = QdrantClient("http://localhost:6333")

# Prepare your documents, metadata, and IDs
docs = ["Qdrant has Langchain integrations", "Qdrant also has Llama Index integrations"]
metadatas = [
    {"source": "Langchain-docs"},
    {"source": "Linkedin-docs"},
]
ids = [42, 2]

# Use the new add method
client.add(collection_name="demo_collection", documents={"documents": docs, "metadatas": metadatas, "ids": ids})

search_result = client.query(collection_name="demo_collection", query_texts=["This is a query document"])
print(search_result)


```

**Comment by phantomdenkali** [comment]
Looks like a duplicate of: https://github.com/qdrant/qdrant-client/issues/269

It would be good if the docs are fixed until the new version is released to avoid others running into this.

**Comment by joein** [comment]
hello @phantomdenkali 

thanks for pointing it out
we were a bit in a hurry :(

release is coming soon (hrs-days) and it won't be needed to fix the docs

**Comment by joein** [comment]
`fastembed` support was added in 1.5.0, there were minor bugs, which were fixed in the next releases (it is considered safe to use qdrant-client >= 1.5.4
