### ISSUE TITLE
ValidationError: 101 validation errors for PointStruct vector -> 0 value is not a valid float (type=type_error.float)

### ISSUE THREAD

**Issue by zeynepiskndr** [qdrant/qdrant-client#279]
### Current Behavior

```
vectors = []
for image in images:
     img = cv2.imread(f"{saved_images_path}/{image}")
     image_embedding = img_encoder(img)
     vectors.append(image_embedding)
```

this way I create my vectors and throw them into the vectors array. then I reformat it to be float64.

`np_vectors = np.array(vectors,dtype="float64")
`
Finally, I export these vectors to qrant, but I get an invalid float error.

```
import numpy as np
from qdrant_client.models import PointStruct

qdrant_client.upsert(
     collection_name=my_collection,
     points=[
         PointStruct(
             id=i,
             vector=np_vectors.tolist(),
             payload=payload
         )
         for i in index
     ]
)
```

### Expected Behavior

The vectors I created are working without error by qdrant.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):last version
- OS(Ubuntu or CentOS):Google Cloud vertexAI
- CPU/Memory:8 vCPUs, 52 GB RAM
- GPU:No
```

**Comment by joein** [comment]
hey

from the first look it seems like you needed to set `vector=np_vectors[i].tolist()` instead of `vector=np_vectors.tolist()`

**Comment by joein** [comment]
@zeynepiskndr is the issue still actual for you or we can close it?

**Comment by zeynepiskndr** [comment]
@joein I appreciate your help. problem solved.
