### ISSUE TITLE
How to jsonify a ScoredPoint or PointGroup

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant-client#286]
Is there a nice way to jsonify ScoredPoint or PointGroup in python??
If its not possible, please let me know the answer to the next question
A section of my search_group result is 
('groups', [PointGroup(hits=[ScoredPoint(id='196644f5-99cf-51be-b7ba-e7e20b981ed2', version=460625, score=0.5977945, payload={'emb_type': False, 'embedding_id': '9:XYZ.xmlFalse', 'file': 'XYZ.xml'

How do I access the individual 'file' elements?

**Comment by generall** [comment]
https://docs.pydantic.dev/latest/usage/serialization/
