### ISSUE TITLE
Getting "lookup":null

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant-client#296]
Hi in case of group search, Im getting "lookup" as null.

This is my code section
        with_lookup=models.WithLookup(
            # Name of the collection to look up points in
            collection="us_fto_collection_master",

            # Options for specifying what to bring from the payload
            # of the looked up point, True by default
            with_payload=["file", "file_uuid"],

            # Options for specifying what to bring from the vector(s)
            # of the looked up point, True by default
            with_vectors=False,
        )

I need all fields from inner collection to return but behaviou doesnt change if I make with_payload=True,

**Comment by nairajay2k** [comment]
No I didnt. I was looking up a normal string..Now corrected.

Thanks

**Comment by joein** [comment]
@nairajay2k i have create the issue to improve our docs in `Lookup in groups`

Can issues you've created be closed or is there any problem remaining?

**Comment by nairajay2k** [comment]
Please close
