### ISSUE TITLE
how do i load a point by id

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant-client#297]
pl provide python code for loading / retrieving a point by id or a list of ids

**Comment by tmckerihan** [comment]
Can use the retrieve method, detailed here:
https://qdrant.tech/documentation/concepts/points/#retrieve-points

Note it has parameters for also returning the vectors and payload (returns neither by default)

**Comment by joein** [comment]
Yes, the answer is correct, except the payload is returned by default
