### ISSUE TITLE
Memory mode Vector inputs different to outputs

### ISSUE THREAD

**Issue by tmckerihan** [qdrant/qdrant-client#298]
Upserting a set of vector points into a ":memory" instantiated client and then reading the points back out using the retrieve() method returns a different vector than what was inserted.

**Note:** 
- Have not yet tried to replicate outside of ":memory:" client
- Issues appear to occur on qdrant-client versions >=1.3.2 so maybe Pydantic 2 related
- Originally identified the issue in code using vectors of size 1536, so size does not seem related

Minimal code to reproduce:

```python
import uuid

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, PointStruct, VectorParams

id = str(uuid.uuid1().int)[:32]
vector = [1.0] * 10
print("vector in:")
print(vector)

vector_client = QdrantClient(":memory:")
vector_client.recreate_collection(
    collection_name="main",
    vectors_config=VectorParams(size=10, distance=Distance.COSINE),
)

vector_client.upsert(
    collection_name="main",
    points=[PointStruct(id=id, vector=vector, payload={})],
)

embeddings = vector_client.retrieve(collection_name="main", ids=[id], with_vectors=True)
print("\nvector out:")
print(embeddings[0])
```

Output:
vector in:
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

vector out:
id='10474983846767374479765544369770' payload={} vector=[0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201, 0.3162277638912201]

## System Information
Macbook Pro M1
Python Version 3.11.5
### Pip freeze output
annotated-types==0.5.0
anyio==4.0.0
certifi==2023.7.22
grpcio==1.58.0
grpcio-tools==1.58.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.18.0
httpx==0.25.0
hyperframe==6.0.1
idna==3.4
numpy==1.25.2
portalocker==2.7.0
protobuf==4.24.3
pydantic==2.3.0
pydantic_core==2.6.3
qdrant-client==1.5.4
sniffio==1.3.0
typing_extensions==4.7.1
urllib3==1.26.16

**Comment by joein** [comment]
Hello @tmckerihan, when you use Distance.COSINE, qdrant does normalization to make further operations more performant, it should be the same in the server mode

**Comment by tmckerihan** [comment]
Okay thankyou joein, was looking into default quantization changes in the changelog, didn't think of checking changes to normalization too. Thanks for clarifying, makes sense!
