### ISSUE TITLE
vectors_count increases and then decreases

### ISSUE THREAD

**Issue by nairajay2k** [qdrant/qdrant-client#303]
Hi,

When I query a collection that Im upserting to like
curl -X GET "http://my_ip:6333/collections/my_collection"

I get "vectors_count","indexed_vectors_count","points_count".
Now the 1st and 3rd counts increase and then surprisingly decrease also. This is also the behavior with the indexed_vectors_count but not to that extent.
Im not sure why there should be a decrease when the only operation being performed is upserts.

Thanks
Ajay

**Comment by joein** [comment]
Hi @nairajay2k 

It is possible to have more points then you expect during uploading process due to optimization processes, but at the end there should be exactly the amount of point you've uploaded
