### ISSUE TITLE
HTTPX deprecation warning

### ISSUE THREAD

**Issue by JanBeelte** [qdrant/qdrant-client#310]
Hello,

when I use the library I get:
`python3.11/site-packages/httpx/_content.py:204: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.`
according to the [documentation](https://www.python-httpx.org/compatibility/) this will be removed with 1.0 .
The fix also seems pretty straight forward from a first glance.

Best,
Jan

**Comment by joein** [comment]
Hi @JanBeelte, thanks for pointing it out

Update should be available in the next release

You can try it out in `dev` branch

Feel free to re-open the issue if it persists
