### ISSUE TITLE
Error pydantic version compatibility with qdrant-client

### ISSUE THREAD

**Issue by clementapa** [qdrant/qdrant-client#315]
```
entity = PointStruct(id=0, vector=torch.rand(512), payload=payload)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for PointStruct
vector.list[float]
  List should have at most 10 items after validation, not 11 [type=too_long, input_value=tensor([6.7944e-01, 3.449...1.8599e-02, 6.8695e-01]), input_type=Tensor]
    For further information visit https://errors.pydantic.dev/2.4/v/too_long
vector.dict[str,list[float]]
  Input should be a valid dictionary [type=dict_type, input_value=tensor([6.7944e-01, 3.449...1.8599e-02, 6.8695e-01]), input_type=Tensor]
    For further information visit https://errors.pydantic.dev/2.4/v/dict_type
```

Hello, 
`pydantic` version 2.4.0 is not compatible with `qdrant-client` 1.5.0 and 1.4

**Comment by joein** [comment]
Hi @clementapa, from the first glance it seems like `pydantic` was converting np arrays, tensors, etc to list, if model was defined with a field of type list and now `pydantic` has stopped doing thas. `PointStruct` actually never had np arrays, tensors among its supported types. 
Could you please try to pass lists instead of tensors to your `PointStruct`? (It worked for me)

**Comment by frutik** [comment]
I have similar error

`(base) frutik@OLDTIMER product_reviews % pip freeze | grep -i -E 'pydantic|qdrant'
pydantic==2.4.2
pydantic_core==2.10.1
qdrant-client==1.5.4
(base) frutik@OLDTIMER product_reviews % python buildindex.py
  0%|                                                                                                                | 0/75000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Volumes/PHILIPS Solid S/data/product_reviews/buildindex.py", line 27, in <module>
    PointStruct(
  File "/Users/frutik/miniconda3/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PointStruct
id
  Field required [type=missing, input_value={'vector': [-0.0147566515..., 0.006557128392159939]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing`

**Comment by joein** [comment]
your error is  `1 validation error for PointStruct id Field required` which means that you didn't set `id` during creating `PointStruct`
