### ISSUE TITLE
Python type hints for the grpc client

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant-client#321]
I'm using the pb2 stubs, because they are async, but to improve the UX it would be nice to have type hints for autosuggestion, and to avoid type errors like:

```
Expected no arguments to "CreateCollection" constructor
```

<img width="700" alt="CleanShot 2023-09-30 at 22 36 09@2x" src="https://github.com/qdrant/qdrant-client/assets/125105/699fb1f2-2f6a-43bd-913a-b9c30187067d">

**Comment by joein** [comment]
Not sure whether we can actually do anything with grpc type hints since grpc is auto generated

However more common interface will be delivered soon for async and you won't be needed to use this grpc constructions https://github.com/qdrant/qdrant-client/pull/319

**Comment by joein** [comment]
as of 1.6.1 AsyncQdrantClient is available, it provides an async version of a regular QdrantClient's interface
