### ISSUE TITLE
Method to save :memory: index to file

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [qdrant/qdrant-client#333]
I'd like to be able to use Qdrant without a server, or at least use it in-memory until the index size becomes large enough to require disk and a running qdrant server.

Can there be a function to create a backup from a currently running in-memory index via the python qdrant client?

**Comment by joein** [comment]
Hello @dhruv-anand-aintech 
Local mode in Qdrant is not designed to handle large amount of data (in general not more than 100k vectors)

To store your storage in local mode you can set `path` argument

**Comment by dhruv-anand-aintech** [comment]
Ok. But is there a way to transfer the data in that path to a running qdrant server?

**Comment by joein** [comment]
yes, you can use `.migrate` method in the client

**Comment by dhruv-anand-aintech** [comment]
Thanks!
