### ISSUE TITLE
Replace duplicated SUPPORTED MODELS?

### ISSUE THREAD

**Issue by NirantK** [qdrant/qdrant-client#341]
We maintain a duplicate copy of supported models here at the Qdrant client and FastEmbed both: https://github.com/qdrant/qdrant-client/blob/a54448b97ab8993932e51139c8fce101817b1774/qdrant_client/qdrant_fastembed.py#L18

Should we use the same function in both places? The FastEmbed API does not mention the distance metric right now, but we can add that, making it a single source of truth?

**Comment by joein** [comment]
closing as already implemented
