### ISSUE TITLE
getting all points in a collection

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [qdrant/qdrant-client#344]
Hi there 👋 

I have stored some points using langchain and I am trying to retrieve them by

```python
from qdrant_client import QdrantClient
from langchain.vectorstores.qdrant import Qdrant

client = QdrantClient()

print(client.get_collection("test"))

print(client.rest.points_api.get_points("test"))
```

However I get 

```
b'{"status":{"error":"Format error in JSON body: EOF while parsing a value at line 1 column 0"},"time":0.0}'
```

On the UI my collection looks like:

<img width="1387" alt="Screenshot 2023-10-20 at 11 47 46" src="https://github.com/qdrant/qdrant-client/assets/15908060/d57a0bcb-3c10-4b25-a0bd-d7f0e1051ab7">

Thanks a lot in advance

**Comment by joein** [comment]
Hi @FrancescoSaverioZuppichini 

To retrieve points you need to provide some info about them, like ids or filters

By the way where did you find a hint to use these internal methods like `client.rest.points_api.get_points`?

You can use them, but I wouldn't say that it is recommended

You probably need to look into the methods like retrieve or scroll of QdrantClient

https://qdrant.tech/documentation/concepts/points/#retrieve-points

https://qdrant.tech/documentation/concepts/points/#scroll-points

**Comment by FrancescoSaverioZuppichini** [comment]
> By the way where did you find a hint to use these internal methods like client.rest.points_api.get_points?

I think somewhere in the doc or in the docstring or in the source code, I can't remember - it was morning hahaha, wondering why is not working

okay, I can use `scroll` 🦾 

Thanks a lot

**Comment by joein** [comment]
Once you are able to accomplish your goal, could you please close the issue?
