### ISSUE TITLE
Is there a way to detect any existing client object and reuse it in python?

### ISSUE THREAD

**Issue by Gilnore** [qdrant/qdrant-client#346]
RuntimeError for the Qdrant client that already exists has been preventing me from completing my Streamlit app. Streamlit has a tendency to re-run the entire script every time the user updates something, this causes my script to constantly spawn objects that already exist, the most problematic of which is the Qdrant client object. I want to find a way to detect any existing client and reuse it. either that or a way to remove and disconnect the client each time after invoking the object. 

How would I go about implementing this?

**Comment by joein** [comment]
@Gilnore hi, have you seen streamlit’s cache resource? I think it might be what you are actually looking for

https://docs.streamlit.io/library/api-reference/performance/st.cache_resource

**Comment by Gilnore** [comment]
> @Gilnore hi, have you seen streamlit’s cache resource? I think it might be what you are actually looking for
> 
> https://docs.streamlit.io/library/api-reference/performance/st.cache_resource

it's complaining about me not using set_page_config as the first line:

streamlit.errors.StreamlitAPIException: `set_page_config()` can only be called once per app page, and must be called as the first Streamlit command in your script.

I don't understand what went wrong, as this error doesn't appear without the decorator. Instead, the qdrant client runtime error appears.

**Comment by joein** [comment]
Unfortunately, it's hard to tell for me what is the reason without seeing your code

**Comment by Gilnore** [comment]
> Unfortunately, it's hard to tell what is the reason without seeing your code or a reproducible code snippet

Thanks anyway. I just changed my code to exclude that one line from my function, and moved it outside. It didn't fix everything, but at least have a different error now.
