### ISSUE TITLE
ImportError: cannot import name 'QdrantClient' from partially initialized module 'qdrant_client' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Dylan-JD** [qdrant/qdrant-client#347]
how to solve this problem?, my env is python 3.8

ImportError: cannot import name 'QdrantClient' from partially initialized module 'qdrant_client' (most likely due to a circular import)

**Comment by joein** [comment]
Hi, which qdrant-client version do you use?
Could you show the structure of your working dir? Do you have directories named qdrant_client?

**Comment by Dylan-JD** [comment]
oh, make sense. Sorry, I forget that I have named my work dir as qdrant-client.py

Thanks a lot
