### ISSUE TITLE
Document upload_collection

### ISSUE THREAD

**Issue by Uzay-G** [qdrant/qdrant-client#35]
It would be nice to document this part of the API in the README, seems pretty essential to the whole flow:

https://github.com/qdrant/qdrant_client/blob/38ffdcb51ca7e2286285445aa86e347b2bec0ca0/tests/test_qdrant_client.py#L68-L75

I can make a PR if you'd like.

**Comment by generall** [comment]
Hi @Uzay-G, thanks for pointing that out!  We are planing to have a dedicated web page with docs, will include the description for this method as well

**Comment by joein** [comment]
https://github.com/qdrant/landing_page/pull/454
