### ISSUE TITLE
MaxTimeout 408 Error

### ISSUE THREAD

**Issue by msj121** [qdrant/qdrant-client#358]
```
File "D:\searchit\qdrant\test.py", line 61, in getExistingEpisodes
    episodes = self.toQdrant.scroll("episode", limit=100000, offset=0, filter=Filter(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\searchit\qdrant\test.py", line 57, in scroll
    res = self.client.scroll(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\qdrant_client.py", line 723, in scroll
    return self._client.scroll(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\qdrant_remote.py", line 952, in scroll
    ] = self.openapi_client.points_api.scroll_points(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\http\api\points_api.py", line 1152, in scroll_points
    return self._build_for_scroll_points(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\http\api\points_api.py", line 443, in _build_for_scroll_points
    return self.api_client.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\http\api_client.py", line 74, in request
    return self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\qdrant_client\http\api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 408 (Request Timeout)
Raw response content:
b''
```

I am playing around with qdrant uploading points, and checking if they exist. I do have a lot of vectors and trying to see how well Qdrant does with large datasets.

Before every upload I perform a scroll operation, it is hitting this 408 timeout. On the server I see no error when I check docker <id> logs tail=200

I have increased timeout to 320 but still happens, do I need a larger timeout? Should I batch uploads to larger chunks? I am a little confused about what causes this issue, 64gb Ram 1Tb server...

**edit:*** Using http... is grpc much better for this type of thing?

**Comment by joein** [comment]
Hello @msj121 

I might need to more info to help you
Which OS do you use, which qdrant version do you use, which qdrant-client version do you use?

How does you collection info looks like?

Could you please provide a code snippet, how do you create a client?
How do you do your scroll queries?

The more information the better

gRPC can improve the situation a bit, however I don't think that it will help when 320 sec timeout does not help (btw, might need to see how you actually set your timeouts)

**Comment by msj121** [comment]
Both from Windows(11) and Ubuntu(22.04)

Versions:
- Qdrant 1.6.1 (as stated on dashboard)
- Client: 1.6.3 (pip list)
- Python 3.11

TVShow: {title, description, date, mediacompany, rating, actors, contactinfo}
TVEpisode {title,description, date, guests}

Client Creation:
` client = QdrantClient(url,timeout=320,prefer_grpc=True)`

Scroll Called:
```
def scroll(self, collection_name, limit=10, offset=None, filter=None):
        if(offset is None):
            res = self.client.scroll(
                collection_name=collection_name,
                scroll_filter=filter,
                limit=limit,
            )
        else:
            res = self.client.scroll(
                collection_name=collection_name,
                scroll_filter=filter,
                offset=offset,
                limit=limit,
            )
        return res
```

**Comment by joein** [comment]
Could you please show the output of `client.get_collection(<your_collection_name>)`?

Do you actually use payload filters during scroll? If so, have you created payload indices?

**Comment by msj121** [comment]
Sorry your right - meant to post that:
```
showId = "122-asd-124"
episodes = self.toQdrant.scroll("episode", limit=100000, offset=0, filter=Filter(
            must=[  # These conditions are required for search results
                FieldCondition(
                    key='showId',
                    match=MatchValue(
                        value=showId
                    )
                )
            ]
        ))
```

I use a large limit to get all shows just in case... I had assumed this was not an issue.

Collection:
`
CollectionInfo(status=<CollectionStatus.GREEN: 'green'>, optimizer_status=<OptimizersStatusOneOf.OK: 'ok'>, vectors_count=392159, indexed_vectors_count=0, points_count=392159, segments_count=8, config=CollectionConfig(params=CollectionParams(vectors=VectorParams(size=384, distance=<Distance.COSINE: 'Cosine'>, hnsw_config=None, quantization_config=None, on_disk=True), shard_number=1, replication_factor=1, write_consistency_factor=1, read_fan_out_factor=None, on_disk_payload=True), hnsw_config=HnswConfig(m=16, ef_construct=100, full_scan_threshold=10000, max_indexing_threads=0, on_disk=False, payload_m=None), optimizer_config=OptimizersConfig(deleted_threshold=0.2, vacuum_min_vector_number=1000, default_segment_number=0, max_segment_size=None, memmap_threshold=None, indexing_threshold=0, flush_interval_sec=5, max_optimization_threads=1), wal_config=WalConfig(wal_capacity_mb=32, wal_segments_ahead=0), quantization_config=None), payload_schema={'showId': PayloadIndexInfo(data_type=<PayloadSchemaType.KEYWORD: 'keyword'>, params=None, points=392159)})`

**Comment by joein** [comment]
wow, `limit=100_000` - that's a lot, i wouldn't expect it to complete fast, it would probably be better to use lower limits and use pagination to scroll through all those pages

Also it might be worth checking whether you have fast enough disks

Firstly, if you store your vectors on disk, than HDDs are not enough for such setup, you need SSD
Secondly, if you have SSDs, you need fast ones

**Comment by msj121** [comment]
But in reality there are only like 100-1000 for all, I just put it high to capture any case - do you think that lowering the number would solve the issue?

**Comment by joein** [comment]
limit=100 is a somewhat doable, i wouldn't go much further

how much time does a search query with `limit=10` and `query_filter=None` require to complete?

**Comment by msj121** [comment]
0.3 seconds last time I checked for checking and updating. On the host machine, but specifically for checking I recall getting 0.03 seconds on a remote machine.
