### ISSUE TITLE
urllib3 = "^1.26.14" are there plans to migrate to urllib3 ~2.0

### ISSUE THREAD

**Issue by domik82** [qdrant/qdrant-client#374]
According to 
https://github.com/qdrant/qdrant-client/blob/d6100614fd2b8413781763d57013f0ee376741e1/pyproject.toml#L27C1-L27C21

This client is only allowed to use urllib3 = "^1.26.14"
Without migration to 2.0/2.1 it might hold back some other projects due to diamond dependency. Are there plans to migrate?

**Comment by stefanknegt** [comment]
Also interested in this

**Comment by sfitts** [comment]
This has us blocked at the `0.11.9` version of this library since we need `urllib>=2.0.x` for another library.  Of course, being stuck there is now blocking an update to langchain.  So, it's a bit of a mess.

**Comment by joein** [comment]
Hello, thanks for pointing it out!

We are considering unfreezing this dependency, but first we would need to solve this #310

**Comment by joein** [comment]
#418

**Comment by joein** [comment]
Should be available with the next release

Closing for now, feel free to re-open if won't work in the next release
