### ISSUE TITLE
"The read operation timed out"

### ISSUE THREAD

**Issue by thedoor76** [qdrant/qdrant-client#380]
I am unable to interact with qdrant via the qdrant-client this morning.

I was running qdrant-client 1.3.1, so I upgraded to 1.6.9 to make sure. I still get the same error, which is:

> Exception has occurred: ResponseHandlingException
> The read operation timed out
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> httpcore.ReadTimeout: The read operation timed out
> 
> The above exception was the direct cause of the following exception:
> 
> httpx.ReadTimeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
>   File "D:\Projects\python\Qdrant-client-test\test.py", line 12, in <module>
>     hits = client.search(
> qdrant_client.http.exceptions.ResponseHandlingException: The read operation timed out

I can reproduce this at will with this simple routine:
```
from qdrant_client import QdrantClient
from qdrant_client.models import Filter, FieldCondition, MatchValue
import numpy as np

client = QdrantClient(host="[host_address_here]", api_key="[api_key_here]", https=True)

query_vector = np.random.rand(1536)
flt = Filter(must=[FieldCondition(key="documentUIN",
                match=MatchValue(value="XX/0000"))])

hits = client.search(
    "[collection_name]",
    query_vector=query_vector,
    query_filter=flt,
    limit=5  # Return 5 closest points
)    
```

**Comment by joein** [comment]
Hi, have you built payload index for the fields you use in `query_filter` ?

Have you checked our database optimization advice in https://qdrant.tech/documentation/faq/database-optimization/#my-requests-are-very-slow-or-time-out-what-should-i-do ?

Are your client and server located in the same area? (It is recommended to have clients and servers in the same geo-region?)

**Comment by joein** [comment]
Closing this one due to the lack of activity

**Comment by alvitawa** [comment]
I just got this as well today. Waited 5 minutes and ran it again and then it worked. I have had it before too, seems qdrant needs to ''warm up" after not being used for a while or something.

**Comment by dvrbanic-syntio** [comment]
Hi,

Did you find a breakthrough? I encountered the same error after running `Qdrant.from_documents(...)`.

Could I potentially resolve it by setting the timeout parameter like this: `Qdrant.from_documents(timeout=60, ...)`?

**Comment by rcanelav** [comment]
Im getting this error on .recreate_collection method

**Comment by jmohren** [comment]
> I just got this as well today. Waited 5 minutes and ran it again and then it worked. I have had it before too, seems qdrant needs to ''warm up" after not being used for a while or something.

@joein I have the same issue, it is hard to reproduce the error but sometimes we get a time out error when making a request to Qdrant. After waiting a bit and running the same request it seems to be working reliably. Is it a possibility that Qdrant can go in some sort of sleep mode and therefore needs a little bit to start up after no requests are send for a while?

**Comment by joein** [comment]
@jmohren are you using any `on-disk` options?

**Comment by jmohren** [comment]
@joein This is our collection config, hope this helps and thanks for the help!

{"params":{"vectors":{"dense":{"size":754,"distance":"Cosine"}},"shard_number":1,"replication_factor":1,"write_consistency_factor":1,"on_disk_payload":true,"sparse_vectors":{"sparse":{"index":{"on_disk":false}}}},"hnsw_config":{"m":16,"ef_construct":100,"full_scan_threshold":10000,"max_indexing_threads":0,"on_disk":false},"optimizer_config":{"deleted_threshold":0.2,"vacuum_min_vector_number":1000,"default_segment_number":0,"max_segment_size":null,"memmap_threshold":null,"indexing_threshold":20000,"flush_interval_sec":5,"max_optimization_threads":null},"wal_config":{"wal_capacity_mb":32,"wal_segments_ahead":0},"quantization_config":null}

**Comment by lsshawn** [comment]
@joein i have the same experience with @jmohren  and it feels like a sleep mode.

This is how i run qdrant:

> docker run -d -p 6333:6333  -v /home/ss/qdrant/config/prod.yaml:/qdrant/config/production.yaml  --ulimit nofile=100000:100000     qdrant/qdrant

my `prod.yaml` configuration is simple:

```
