### ISSUE TITLE
Question about QdrantLocal

### ISSUE THREAD

**Issue by hanqiushi** [qdrant/qdrant-client#381]
Is there any way we can save RAM when using QdrantLocal ? I tried different params, didn't find a way to save RAM when launching service.
Below is my test code:

client = QdrantClient(path="./data-db")  # Persists changes to disk

client.create_collection(
        collection_name="xxx",
        vectors_config=models.VectorParams(size=384, distance=models.Distance.COSINE, on_disk=True,
                                        hnsw_config=models.HnswConfigDiff(on_disk=True)),
        optimizers_config=models.OptimizersConfigDiff(memmap_threshold=0),
        on_disk_payload=True,
        quantization_config=models.ScalarQuantization(
            scalar=models.ScalarQuantizationConfig(
                type=models.ScalarType.INT8,
                always_ram=False,
            ),
        ),
    )

**Comment by joein** [comment]
@hanqiushi hi, could you describe your setup?
How many points do you want to store in local mode?

Please, keep in mind that local mode has not been designed to be used in production, it is a tool for fast experiments.
Once you are done with lightweight experiments - you can switch to qdrant server with just replacing `path=...` to `url=...` (qdrant server can be e.g.  qdrant launched in docker locally, or any other kind of deployment like cloud or your k8s cluster)

**Comment by joein** [comment]
@hanqiushi hi, is this question still actual, or I can close the issue?
