### ISSUE TITLE
embedding is None in query reponse

### ISSUE THREAD

**Issue by DiTo97** [qdrant/qdrant-client#382]
I have been following the examples proposed in the README, but the search response always has empty embeddings.

Am I missing something? fastembed has been correctly installed with:

```shell
python -m pip install qdrant-client[fastembed]
```

**Comment by joein** [comment]
Hi @DiTo97 

Could you send a code sample of how you search?

The problem is probably in `with_vectors` argument, you need to set it to `True` in search operations so they would return vectors in response

**Comment by DiTo97** [comment]
Hi @joein,

I had been trying the example in the README, but I can confirm it's not working as expected after adding the `with_vectors` arg.

The example is the following:
```python
import qdrant_client

# Initialize the client
client = qdrant_client.QdrantClient(":memory:")

# Prepare your documents, metadata, and IDs
docs = ["Qdrant has Langchain integrations", "Qdrant also has Llama Index integrations"]
metadata = [
    {"source": "Langchain-docs"},
    {"source": "Linkedin-docs"},
]
ids = [42, 2]

# Use the new add method
client.add(
    collection_name="demo_collection",
    documents=docs,
    metadata=metadata,
    ids=ids
)

search_result = client.query(
    collection_name="demo_collection",
    query_text="This is a query document"
)
print(search_result)
```
