### ISSUE TITLE
contextual search retrieval with vector metadata?

### ISSUE THREAD

**Issue by DiTo97** [qdrant/qdrant-client#383]
I have a bunch of phrases and senteces, each accompanied with a non-semantic embedding generated by some model.

Is there away to enable fast retrieval with Qdrant such that the output depends on both the similarity of the semantic embedding generated by fastembed and the similarity of the provided contextual embedding?

**Comment by joein** [comment]
Hi @DiTo97 

This functionality is not provided by Qdrant out-of-the-box
However, how would you like it to work?

Fetch N results by semantic embeddings + rescore them with non-semantic embeddings?
If the answer is yes, then I think it can be done manually without a significant drop in performance

**Comment by joein** [comment]
Could you provide a link where have you seen that?

**Comment by DiTo97** [comment]
> Could you provide a link where have you seen that?

seen what? The re-ranking algorithm or that a join search peforms a bit better?

**Comment by joein** [comment]
join search

**Comment by DiTo97** [comment]
For that, I cannot share the dataset as it's a client's private dataset. For now, I just extracted the embedding from each document using fastembed and wrote a numba kernel that combines the two distances for joint similarity.

In general, it might not be true, but it is the case for the dataset I have at hand.

That's why I was asking if Qdrant had that, to move the codebase using that.

**Comment by joein** [comment]
I am wondering how this joint similarity is computed / used, so if you could provide a link to numba doing that, would be appreciated
