### ISSUE TITLE
Reason behind the python version cap?

### ISSUE THREAD

**Issue by baggiponte** [qdrant/qdrant-client#390]
Hi! Thanks for the great work. I wanted to ask the reasoning behind capping the Python version to be smaller than `3.13` [here](https://github.com/qdrant/qdrant-client/blob/8875b45feac121d499e4939d395d5a9e1c39da51/pyproject.toml#L17). Are there any components susceptible to breaking changes in the CPython API? This upper boundary constraint is inherited by any library that depends on qdrant-client, e.g. llama-index.

**Comment by joein** [comment]
We are going to unlock it #419 

Should be available with the next version

**Comment by baggiponte** [comment]
Thanks!
