### ISSUE TITLE
resolve a misleading comment in method query_embed

### ISSUE THREAD

**Issue by jsjsam98** [qdrant/qdrant-client#402]
the query_embed method in embedding.py has a comment as ‘# Compute the cosine similarity between the query embedding and the document embeddings’, but it is not doing any cosine similarity computing indeed

**Comment by manijhariya** [comment]
Can you drop full file path here. I am not able to find this particular file.

**Comment by joein** [comment]
I believe it has already been resolved here
https://github.com/qdrant/fastembed/commit/219185e6770b6dc49e2f9cd0db6ab6039874e1d9

**Comment by jsjsam98** [comment]
got it!

________________________________
