### ISSUE TITLE
ResponseHandlingException: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by runiaruni** [qdrant/qdrant-client#410]
I have tried running the following code:
`client = qdrant_client.QdrantClient("qdrant_index", port=6333, grpc_port=6333)`

`text_store = QdrantVectorStore(
    client=client, collection_name="text_collection"
)`

And I have been stuck on the following error for a few days:

> 
> {
> 	"name": "ResponseHandlingException",
> 	"message": "[Errno -2] Name or service not known",
> 	"stack": "---------------------------------------------------------------------------
> gaierror                                  Traceback (most recent call last)
> File ~/.local/lib/python3.10/site-packages/httpcore/_exceptions.py:10, in map_exceptions(map)
>       9 try:
> ---> 10     yield
>      11 except Exception as exc:  # noqa: PIE786
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py:206, in SyncBackend.connect_tcp(self, host, port, timeout, local_address, socket_options)
>     205 with map_exceptions(exc_map):
> --> 206     sock = socket.create_connection(
>     207         address,
>     208         timeout,
>     209         source_address=source_address,
>     210     )
>     211     for option in socket_options:
> 
> File /usr/lib/python3.10/socket.py:824, in create_connection(address, timeout, source_address)
>     823 err = None
> --> 824 for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>     825     af, socktype, proto, canonname, sa = res
> 
> File /usr/lib/python3.10/socket.py:955, in getaddrinfo(host, port, family, type, proto, flags)
>     954 addrlist = []
> --> 955 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>     956     af, socktype, proto, canonname, sa = res
> 
> gaierror: [Errno -2] Name or service not known
> 
> The above exception was the direct cause of the following exception:
> 
> ConnectError                              Traceback (most recent call last)
> File ~/.local/lib/python3.10/site-packages/httpx/_transports/default.py:66, in map_httpcore_exceptions()
>      65 try:
> ---> 66     yield
>      67 except Exception as exc:
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_transports/default.py:228, in HTTPTransport.handle_request(self, request)
>     227 with map_httpcore_exceptions():
> --> 228     resp = self._pool.handle_request(req)
>     230 assert isinstance(resp.stream, typing.Iterable)
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py:268, in ConnectionPool.handle_request(self, request)
>     267         self.response_closed(status)
> --> 268     raise exc
>     269 else:
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py:251, in ConnectionPool.handle_request(self, request)
>     250 try:
> --> 251     response = connection.handle_request(request)
>     252 except ConnectionNotAvailable:
>     253     # The ConnectionNotAvailable exception is a special case, that
>     254     # indicates we need to retry the request on a new connection.
>    (...)
>     258     # might end up as an HTTP/2 connection, but which actually ends
>     259     # up as HTTP/1.1.
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py:99, in HTTPConnection.handle_request(self, request)
>      98         self._connect_failed = True
> ---> 99         raise exc
>     100 elif not self._connection.is_available():
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py:76, in HTTPConnection.handle_request(self, request)
>      75 try:
> ---> 76     stream = self._connect(request)
>      78     ssl_object = stream.get_extra_info(\"ssl_object\")
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py:124, in HTTPConnection._connect(self, request)
>     123 with Trace(\"connect_tcp\", logger, request, kwargs) as trace:
> --> 124     stream = self._network_backend.connect_tcp(**kwargs)
>     125     trace.return_value = stream
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py:205, in SyncBackend.connect_tcp(self, host, port, timeout, local_address, socket_options)
>     200 exc_map: ExceptionMapping = {
>     201     socket.timeout: ConnectTimeout,
>     202     OSError: ConnectError,
>     203 }
> --> 205 with map_exceptions(exc_map):
>     206     sock = socket.create_connection(
>     207         address,
>     208         timeout,
>     209         source_address=source_address,
>     210     )
> 
> File /usr/lib/python3.10/contextlib.py:153, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
>     152 try:
> --> 153     self.gen.throw(typ, value, traceback)
>     154 except StopIteration as exc:
>     155     # Suppress StopIteration *unless* it's the same exception that
>     156     # was passed to throw().  This prevents a StopIteration
>     157     # raised inside the \"with\" statement from being suppressed.
> 
> File ~/.local/lib/python3.10/site-packages/httpcore/_exceptions.py:14, in map_exceptions(map)
>      13     if isinstance(exc, from_exc):
> ---> 14         raise to_exc(exc) from exc
>      15 raise
> 
> ConnectError: [Errno -2] Name or service not known
> 
> The above exception was the direct cause of the following exception:
> 
> ConnectError                              Traceback (most recent call last)
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:101, in ApiClient.send_inner(self, request)
>     100 try:
> --> 101     response = self._client.send(request)
>     102 except Exception as e:
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_client.py:901, in Client.send(self, request, stream, auth, follow_redirects)
>     899 auth = self._build_request_auth(request, auth)
> --> 901 response = self._send_handling_auth(
>     902     request,
>     903     auth=auth,
>     904     follow_redirects=follow_redirects,
>     905     history=[],
>     906 )
>     907 try:
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_client.py:929, in Client._send_handling_auth(self, request, auth, follow_redirects, history)
>     928 while True:
> --> 929     response = self._send_handling_redirects(
>     930         request,
>     931         follow_redirects=follow_redirects,
>     932         history=history,
>     933     )
>     934     try:
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_client.py:966, in Client._send_handling_redirects(self, request, follow_redirects, history)
>     964     hook(request)
> --> 966 response = self._send_single_request(request)
>     967 try:
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_client.py:1002, in Client._send_single_request(self, request)
>    1001 with request_context(request=request):
> -> 1002     response = transport.handle_request(request)
>    1004 assert isinstance(response.stream, SyncByteStream)
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_transports/default.py:227, in HTTPTransport.handle_request(self, request)
>     215 req = httpcore.Request(
>     216     method=request.method,
>     217     url=httpcore.URL(
>    (...)
>     225     extensions=request.extensions,
>     226 )
> --> 227 with map_httpcore_exceptions():
>     228     resp = self._pool.handle_request(req)
> 
> File /usr/lib/python3.10/contextlib.py:153, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
>     152 try:
> --> 153     self.gen.throw(typ, value, traceback)
>     154 except StopIteration as exc:
>     155     # Suppress StopIteration *unless* it's the same exception that
>     156     # was passed to throw().  This prevents a StopIteration
>     157     # raised inside the \"with\" statement from being suppressed.
> 
> File ~/.local/lib/python3.10/site-packages/httpx/_transports/default.py:83, in map_httpcore_exceptions()
>      82 message = str(exc)
> ---> 83 raise mapped_exc(message) from exc
> 
> ConnectError: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> ResponseHandlingException                 Traceback (most recent call last)
> Cell In[41], line 1
> ----> 1 text_store = QdrantVectorStore(
>       2     client=client, collection_name=\"text_collection\"
>       3 )
> 
> File ~/.local/lib/python3.10/site-packages/llama_index/vector_stores/qdrant.py:81, in QdrantVectorStore.__init__(self, collection_name, client, url, api_key, batch_size, prefer_grpc, client_kwargs, **kwargs)
>      78 else:
>      79     self._client = cast(qdrant_client.QdrantClient, client)
> ---> 81 self._collection_initialized = self._collection_exists(collection_name)
>      83 super().__init__(
>      84     collection_name=collection_name,
>      85     url=url,
>    (...)
>      89     client_kwargs=client_kwargs or {},
>      90 )
> 
> File ~/.local/lib/python3.10/site-packages/llama_index/vector_stores/qdrant.py:335, in QdrantVectorStore._collection_exists(self, collection_name)
>     332 from qdrant_client.http.exceptions import UnexpectedResponse
>     334 try:
> --> 335     self._client.get_collection(collection_name)
>     336 except (RpcError, UnexpectedResponse, ValueError):
>     337     return False
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/qdrant_client.py:1527, in QdrantClient.get_collection(self, collection_name, **kwargs)
>    1517 \"\"\"Get detailed information about specified existing collection
>    1518 
>    1519 Args:
>    (...)
>    1523     Detailed information about the collection
>    1524 \"\"\"
>    1525 assert len(kwargs) == 0, f\"Unknown arguments: {list(kwargs.keys())}\"
> -> 1527 return self._client.get_collection(collection_name=collection_name, **kwargs)
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py:1956, in QdrantRemote.get_collection(self, collection_name, **kwargs)
>    1949 if self._prefer_grpc:
>    1950     return GrpcToRest.convert_collection_info(
>    1951         self.grpc_collections.Get(
>    1952             grpc.GetCollectionInfoRequest(collection_name=collection_name),
>    1953             timeout=self._timeout,
>    1954         ).result
>    1955     )
> -> 1956 result: Optional[types.CollectionInfo] = self.http.collections_api.get_collection(
>    1957     collection_name=collection_name
>    1958 ).result
>    1959 assert result is not None, \"Get collection returned None\"
>    1960 return result
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py:1262, in SyncCollectionsApi.get_collection(self, collection_name)
>    1255 def get_collection(
>    1256     self,
>    1257     collection_name: str,
>    1258 ) -> m.InlineResponse2005:
>    1259     \"\"\"
>    1260     Get detailed information about specified existing collection
>    1261     \"\"\"
> -> 1262     return self._build_for_get_collection(
>    1263         collection_name=collection_name,
>    1264     )
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api/collections_api.py:377, in _CollectionsApi._build_for_get_collection(self, collection_name)
>     372 path_params = {
>     373     \"collection_name\": str(collection_name),
>     374 }
>     376 headers = {}
> --> 377 return self.api_client.request(
>     378     type_=m.InlineResponse2005,
>     379     method=\"GET\",
>     380     url=\"/collections/{collection_name}\",
>     381     headers=headers if headers else None,
>     382     path_params=path_params,
>     383 )
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:74, in ApiClient.request(self, type_, method, url, path_params, **kwargs)
>      72 url = (self.host or \"\") + url.format(**path_params)
>      73 request = self._client.build_request(method, url, **kwargs)
> ---> 74 return self.send(request, type_)
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:91, in ApiClient.send(self, request, type_)
>      90 def send(self, request: Request, type_: Type[T]) -> T:
> ---> 91     response = self.middleware(request, self.send_inner)
>      92     if response.status_code in [200, 201, 202]:
>      93         try:
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:200, in BaseMiddleware.__call__(self, request, call_next)
>     199 def __call__(self, request: Request, call_next: Send) -> Response:
> --> 200     return call_next(request)
> 
> File ~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:103, in ApiClient.send_inner(self, request)
>     101     response = self._client.send(request)
>     102 except Exception as e:
> --> 103     raise ResponseHandlingException(e)
>     104 return response
> 
> ResponseHandlingException: [Errno -2] Name or service not known"
> }

**Comment by retrogtx** [comment]
`ConnectError: [Errno -2] Name or service not known`

Seems like a network error on your device itself

**Comment by shivas1516** [comment]
Can I work on this?

**Comment by generall** [comment]
Is `qdrant_index` a proper host name?

**Comment by joein** [comment]
Closing this issue due to the lack of activity, feel free to re-open in case it still persists
