### ISSUE TITLE
i don`t know why the score is 0.0

### ISSUE THREAD

**Issue by FelixLiu553F** [qdrant/qdrant-client#411]
![img_v3_026g_4596ff45-a695-4af6-b481-911371f068bg](https://github.com/qdrant/qdrant-client/assets/136409316/3adf5d3b-ef07-45f6-9834-cece424f881e)

**Comment by generall** [comment]
Me neither. Could you please provide exact query you're sending to qdrant?
It is impossible to tell from the screenshot what's happening inside your service

**Comment by joein** [comment]
Closing due to the lack of activity and information

Feel free to re-open if the issue still persists
