### ISSUE TITLE
error on windows OS WinError 10061

### ISSUE THREAD

**Issue by Sandy4321** [qdrant/qdrant-client#414]
qdrant_client.http.exceptions.ResponseHandlingException: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by Sandy4321** [comment]
code used
from qdrant_client import QdrantClient
import numpy as np
client = QdrantClient()
from qdrant_client.models import Distance, VectorParams

client.recreate_collection(
    collection_name="my_collection",
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)

**Comment by generall** [comment]
how do you run qdrant server?

**Comment by Sandy4321** [comment]
I did only 
pip install qdrant-client

do i need to do something else ?

**Comment by generall** [comment]
`QdrantClient()` assumes that you are running server on `localhost:6333`, if you want to run local mode (without server) you need to do something like `QdrantClient(":memory:")`

**Comment by Sandy4321** [comment]
great , so code will be ? 

from qdrant_client import QdrantClient
import numpy as np
client = QdrantClient(":memory:")
from qdrant_client.models import Distance, VectorParams

client.recreate_collection(
    collection_name="my_collection",
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)

#client.create_collection("my_collection")
vectors = np.random.rand(100, 100)
client.upsert("my_collection", vectors)
query_vector = np.random.rand(100)
hits = client.search("my_collection", query_vector, limit=5)

**Comment by Sandy4321** [comment]
then I have error
builtins.ValueError: Unsupported type: <class 'numpy.ndarray'>
in line 
client.upsert("my_collection", vectors)

**Comment by Sandy4321** [comment]
i want to calculate embeddings somewhere for example openai or aws or GCP
and then to use qdrant to find most similar embeddings

**Comment by Sandy4321** [comment]
ok 
used this code
#S_qdrant_dec28_N3
#pip install qdrant-client
#pip install fastembed
from qdrant_client.models import Distance, VectorParams
from qdrant_client import QdrantClient

# Initialize the client
client = QdrantClient(":memory:")  # or QdrantClient(path="path/to/db")


client.recreate_collection(
    collection_name="my_collection",
    vectors_config=VectorParams(size=100, distance=Distance.COSINE),
)

import numpy as np
from qdrant_client.models import PointStruct

vectors = np.random.rand(100, 100)
client.upsert(
    collection_name="my_collection",
    points=[
        PointStruct(
            id=idx,
            vector=vector.tolist(),
            payload={"color": "red", "rand_number": idx % 10}
        )
        for idx, vector in enumerate(vectors)
    ]
)

query_vector = np.random.rand(100)
hits = client.search(
    collection_name="my_collection",
    query_vector=query_vector,
    limit=5  # Return 5 closest points
)

q = 0


then got
hits[0]
ScoredPoint(id=57, version=0, score=0.8092373398642527, payload={'color': 'red', 'rand_number': 7}, vector=None, shard_key=None)
hits[1]
ScoredPoint(id=17, version=0, score=0.7908989358290599, payload={'color': 'red', 'rand_number': 7}, vector=None, shard_key=None)
hits[2]
ScoredPoint(id=58, version=0, score=0.7884482510530706, payload={'color': 'red', 'rand_number': 8}, vector=None, shard_key=None)
hits[3]
ScoredPoint(id=55, version=0, score=0.7875139901125017, payload={'color': 'red', 'rand_number': 5}, vector=None, shard_key=None)
hits[4]
ScoredPoint(id=89, version=0, score=0.7874128348267135, payload={'color': 'red', 'rand_number': 9}, vector=None, shard_key=None)

what is it 
1 'color': 'red
2 'rand_number': 9
3 version=0

**Comment by generall** [comment]
Sorry I might be not understanding your question.

You created points with some random payload. Now you are searching for those points.

```
1 'color': 'red
2 'rand_number': 9
```

is your payload.

```
version=0
```

is just an update operation ID, you can ignore that

**Comment by Sandy4321** [comment]
I see, by the way, what is mathematical algorithm behind your calculations for similarity for big data , lets say 100 million rows ?
some dimensionality reductions ? 
my guess you do not calculate direct cosine similarity like faiss?

**Comment by joein** [comment]
We calculate cosine similarity, we have low-level optimized code, if you are familiar with Rust, you can check it here

https://github.com/qdrant/qdrant/tree/c6a351c82d57eb786b75dac785de7b085c6f80ff/lib/segment/src/spaces

The underlying vector search algorithm which we use is HNSW

**Comment by joein** [comment]
I guess, the initial issue has been resolved, to avoid ambiguity and ease the further search through answered questions I will close this issue. 

If you have any other questions, you can join our discord server and ask there

1) https://qdrant.to/discord

or if you prefer to stay on github

2) You can use discussions in https://github.com/orgs/qdrant/discussions for core/service related questions

3)  Create a new issue here if the question is related to the client itself


Thanks!

**Comment by dominicdev** [comment]
get this error test llamaIndex
