### ISSUE TITLE
Unable to set cache_dir or max_threads when using client.add(...)

### ISSUE THREAD

**Issue by praveen-palanisamy** [qdrant/qdrant-client#415]
The "native" integration between the `qdrant-client` and [`fastembed`](https://github.com/qdrant/fastembed) packages allows for a simple and neat abstraction via the `client.add(...)` method to automatically create/update/insert `collection` and `Points` using `fastembed`.
But, I am unable to set the `cache_dir` used for the (ONNX) embedding model storage or modify the ONNX Runtime's `intra_op_num_threads` session option via this native integration.
A workaround is to use `fastembed`'s API without using the `qdrant_client.add(...)` method but it defeats the purpose of having this simpler, native API support.

**Comment by joein** [comment]
Should be available in the next version of qdrant-client, thanks for the contribution!
