### ISSUE TITLE
QDrant Client.Query does not work

### ISSUE THREAD

**Issue by rajmsft** [qdrant/qdrant-client#430]
I was able to runt the following yesterday:

qdrant_client.query(
    collection_name="mycollection",
    query_text="what is the fee for Business Tax filing?",
    limit=3,
)

But now I get an error that AttributeError: 'QdrantClient' object has no attribute 'query'.

I created the collection with the default fastembed.

**Comment by joein** [comment]
Hi

Could you please check which version of Qdrant are you running now?
Btw, have you installed fastembed?

**Comment by joein** [comment]
query interface was not supported in 1.2

glad to hear that it works for you with 1.7

closing the issue for now

**Comment by rajmsft** [comment]
Thanks.
Is there a way to get all the meta data from the results. May payload has meta data. I know I can use them to filter the query. How do I get all the associated meta data with the query results?

Thanks,
Raj
________________________________

**Comment by joein** [comment]
By default payload is returned with the results

You can turn it on or off using `with_payload` flag in search (or other operations, e.g. scroll)

**Comment by rajmsft** [comment]
Thanks. I think I was not including the metadata when I added it to the collection. Now it is working.

Raj
________________________________

**Comment by rajmsft** [comment]
We are planning to use Qdrant cloud and want to move to enterprise paid subscription.

We are also looking for consultants who can help with design and implementation.


Is this something you offer as a service, or can you recommend someone?

Thanks
Raj
________________________________

**Comment by joein** [comment]
@rajmsft 

You can find our contacts on this page https://qdrant.tech/pricing/

Or reach out to us in discord https://qdrant.to/discord

**Comment by azayarni** [comment]
@rajmsft please use this form to contact our enterprise team https://qdrant.to/contact-us
