### ISSUE TITLE
Using `models.Batch` with `client.update_vectors`

### ISSUE THREAD

**Issue by fitzgeraldja** [qdrant/qdrant-client#435]
Docs suggest that as for `client.upsert`, `client.update_vectors` (and other ops) should accept a batch defined via `points=models.Batch(...)`, rather than a list of `PointVectors`, but this currently causes a pydantic error

**Comment by joein** [comment]
Hi @fitzgeraldja 

Could you please provide an example?

I tried running this code and there is no error for me

```python
from qdrant_client import QdrantClient, models
client = QdrantClient()
client.recreate_collection('test', vectors_config=models.VectorParams(size=2, distance=models.Distance.COSINE))
client.upsert('test', points=models.Batch(ids=[1,2], vectors=[[0.0, 0.2], [0.1, 0.2]]), wait=True)
```

**Comment by fitzgeraldja** [comment]
I have same dependencies other than python3.10.13 - issue is specifically for `client.update_vectors` rather than `client.upsert`, which in the source code has specific handling for `models.Batch` type points argument. Have tested with 
```python
qdrant.update_vectors(
    collection_name="test",
    points=models.Batch(
        ids=["test-point"],
        vectors={"test-vec": [[np.random.rand() for _ in range(768)]]},
    ),
)
```
for an existing collection

**Comment by joein** [comment]
Some versions of pydantic used to convert numpy arrays to lists implicitly, however it is no longer the case.
Batch structure does not accept numpy arrays on its own, you need to convert it to a list

**Comment by joein** [comment]
Could you please send me a link to the docs when you found that `client.update_vectors` accepts a batch?

**Comment by joein** [comment]
I checked the documentation at qdrant.tech

https://qdrant.tech/documentation/concepts/points/#update-vectors

Example here is indeed incorrect, we will fix it!

It should be a sequence of `PointVectors`. Batch or PointStruct models contain payload field, which is not relevant for update_vectors operation.

**Comment by joein** [comment]
A correct example may look like this:

```
client.update_vectors(
    collection_name=collection_name,
    points=[
        models.PointVectors(
            id=1,
            vector={
                [0.1, 0.1,],
            },
        ),
        models.PointVectors(
            id=2,
            vector={
            [0.2, 0.2],
            },
        ),
    ],
)
```

**Comment by joein** [comment]
https://github.com/qdrant/landing_page/pull/541

**Comment by joein** [comment]
the documentation has been updated
