### ISSUE TITLE
Create a dataframe dataset object 

### ISSUE THREAD

**Issue by GeorgePearse** [qdrant/qdrant-client#450]
So for training, it would be, get the data you want from bigquery, convert it to a dataframe, run some additional filters (is everything available on disk, maybe more advanced frame selection, get some metadata about class counts etc.) then to coco on disk and train 

Dataframe Dataset (could exclusively use duckdb for this too), and BigQuery dataset.

**Comment by GeorgePearse** [comment]
Something like this 

<img width="619" alt="image" src="https://github.com/qdrant/qdrant-client/assets/47161914/8add7629-e896-447d-88e0-7aa147a30964">

**Comment by GeorgePearse** [comment]
```python

import pandas as pd

class DataFrameFilter:
    def __init__(self, dataframe):
        self.dataframe = dataframe
        self.filters = []

    def filter_by_column_value(self, column, value):
        """Filter rows where the specified column matches the given value."""
        self.filters.append(lambda df: df[df[column] == value])
        return self

    def filter_by_custom_function(self, filter_function):
        """Apply a custom filter function to the DataFrame."""
        self.filters.append(filter_function)
        return self

    def apply_filters(self):
        """Apply all accumulated filters and return the filtered DataFrame."""
        filtered_df = self.dataframe
        for filter_func in self.filters:
            filtered_df = filter_func(filtered_df)
        return filtered_df
```

**Comment by GeorgePearse** [comment]
If this had just also had the data_dir as an attribute / didn't feed it through as an argument, it would have worked 

<img width="551" alt="image" src="https://github.com/qdrant/qdrant-client/assets/47161914/1223f013-fef5-4757-a57e-80af7a84dea7">

**Comment by joein** [comment]
Hi @GeorgePearse , long time no see :)

Are you sure it is the right repository for this issue?

**Comment by GeorgePearse** [comment]
Ahaha, definitely not!

**Comment by GeorgePearse** [comment]
Cheers for flagging
