### ISSUE TITLE
Regression: payloads cannot contain python builtin datetime objects in 1.7.1

### ISSUE THREAD

**Issue by TerraformingEarth** [qdrant/qdrant-client#461]
As of 1.7.1 payloads are JSON dumped before loading.

JSON dumping a payload which includes the builtin python datetime object errors with:

`Object of type datetime is not JSON serializable`

This used to work in 1.7.0 as the payloads did not try `json.dumps()`

See [here](https://github.com/qdrant/qdrant-client/compare/v1.7.0...v1.7.1#diff-7289eefffab6a0e4ae17f003f103fe19846b7a034e34de0076ff4b5f67025934R1001) for change in 1.7.1

**Comment by joein** [comment]
Hi, @TerraformingEarth 
Thanks for pointing it out

We will fix it in 1.7.2

**Comment by joein** [comment]
Should be available as of 1.7.2

Feel free to re-open the issue, if the bug persists
