### ISSUE TITLE
Upgrade fastembed version from 0.1.1 to 0.2.1 (latest)

### ISSUE THREAD

**Issue by geetu040** [qdrant/qdrant-client#486]
Currently, qdrant-client uses fastembed version `0.1.1` however there is a latest version of fastembed `0.2.1` available out there.

### Why should it be upgraded?

version `0.1.1` is outdated for qdrant as the latest version `0.2.1` has brough many changes in structure of code and efficiency
There have been following changes by going from `0.1.1` to `0.2.1` in fastembed
- use "with" to open JSON files
- HuggingFace download support for FlagEmbedding
- chore: patch for new Xenova Jina source
- feat: Support xenova/multilingual-e5-large, xenova/paraphrase-multilingual-mpnet-base-v2
- Refactoring of internal structure
- Refactor: Introduce experiments dir, README changes
- Support Python v3.12
- Simplify imports
- Fix query to align with Qdrant mixin usage
- Make 0.2.1 Release + Update docs

### How to change

This can be changed easily by replacing the previous version `0.1.1`
```toml
fastembed = [
    { version = "0.1.1", optional = true, python = "<3.12" }
]
```

With the latest version `0.2.1`
```toml
fastembed = [
    { version = "0.2.1", optional = true, python = "<3.12" }
]
```

### Test Cases

I have run test cases on qdrant with fastembed of both versions to see if any piece of code is affected

Failing Test: [tests/test_fast_embed.py](https://github.com/qdrant/qdrant-client/blob/master/tests/test_fast_embed.py#L120)
```shell
FAILED tests/test_fast_embed.py::test_set_model - AssertionError: assert False
```

### Next Step

If this issue sounds valid, I'll be happy to investigate the failing test case and upgrade to the latest version

**Comment by joein** [comment]
Hm, thanks for pointing out the failing test

Updating version is not the only thing we need to do after the refactoring of fastembed which has been done though

**Comment by geetu040** [comment]
@joein , I was trying to solve this issue from fastembed qdrant/fastembed#95.
Should I wait for fastembed to be upgraded to latest version, or work on currently support version (0.1.1)?

**Comment by geetu040** [comment]
upgraded in #493
