### ISSUE TITLE
Deleting points by ID not working

### ISSUE THREAD

**Issue by abhijeethp** [qdrant/qdrant-client#488]
The following operation does not work.

```python
client.delete(
    collection_name=collection.name,
    points_selector=PointIdsList(points=ids),
)
```

The IDs are the same as used to create the records in the following way : 
```python
client.upsert(
    collection_name=collection.name,
    points=Batch(ids=ids, vectors=vectors, payloads=payloads)
)
```

**Comment by joein** [comment]
hi @abhijeethp 

Could you please provide more details? I can't reproduce it

Could it be by any chance that you are comparing `vectors_count` ? It is actually not a reliable measurement. Could you check `points_count`?

**Comment by joein** [comment]
@abhijeethp is it still relevant? Can I close the issue?

**Comment by abhijeethp** [comment]
@joein I am unfortunately unable to reproduce this issue again. Might have been a transient issue.
 If it persists again then I will re-open an issue with more details. 
 Thanks :)
