### ISSUE TITLE
qdrant_client.QdrantClient never returns

### ISSUE THREAD

**Issue by Dyke-F** [qdrant/qdrant-client#510]
DEFAULT_CLIENT_NAME = "Test1"
QDRANT_COLLECTION_NAME = "Test1"

client = qdrant_client.QdrantClient(
    path=DEFAULT_CLIENT_NAME, collection_name=QDRANT_COLLECTION_NAME
)

The client has already been used to generate collections yesterday (up to 10 GBs of data). 
Loading the client today never returns but keeps on running forever.  No changes have been made in the meantime.
Any suggested solutions?

**Comment by joein** [comment]
Hi @Dyke-F 

How many points do you have?

When you set `path` - qdrant is launched in local mode.
Local mode is not designed to handle a lot of data, maybe it just takes a lot of time to upload everything.

Btw, where did you find an example of passing `collection_name` to `QdrantClient` instance? It does not have such a parameter.

If you could provide a code sample to reproduce the issue, we might try to help.

**Comment by joein** [comment]
closing due to the lack of activity

feel free to reopen if the issue persists
