### ISSUE TITLE
Datetime timezone parsing inconsistency

### ISSUE THREAD

**Issue by coszio** [qdrant/qdrant-client#511]
## Problem
In Qdrant server, we can parse both `+0900` and `+09`-like timezones (with or without the minutes section), while in local mode we can only parse the first variant, the one with the minutes. 

https://github.com/qdrant/qdrant-client/blob/332777db2ad856f4675b27217899383e8c7cd73a/qdrant_client/local/tests/test_datetimes.py#L41-L45

## Expected solution
Local mode should also be able to parse hour-only timezones, like `+02` or `-11`

**Comment by joein** [comment]
available as of `qdrant-client==1.8.1`
