### ISSUE TITLE
UnexpectedResponse: Unexpected Response: 400 (Bad Request) Raw response content: b'{"status":{"error":"Format error in JSON body: data did not match any variant of untagged enum PointInsertOperations"},"time":0.0}'

### ISSUE THREAD

**Issue by thanhlap0572002** [qdrant/qdrant-client#529]
[herecode.txt](https://github.com/qdrant/qdrant-client/files/14522739/herecode.txt)
My data is a folder, inside there is a set of image folders, and I use the folder names to label the image files in the folder.
![image](https://github.com/qdrant/qdrant-client/assets/114754250/38ff501e-408e-4e19-ac44-0bbe43ff3614)

**Comment by Anush008** [comment]
Qdrant only allows UUID strings and unsigned integers as point IDs. You seem to be using a custom label string as ID.

https://qdrant.tech/documentation/concepts/points/#point-ids

**Comment by Anush008** [comment]
Resolved with https://github.com/qdrant/qdrant-client/issues/463.
