### ISSUE TITLE
client.get_collection(...) throws Pydantic validation error

### ISSUE THREAD

**Issue by MixoMax** [qdrant/qdrant-client#547]
When i run this code, i get a Pydantic Validation error:

```py
from qdrant_client import QdrantClient
from qdrant_client.http.models import PointStruct, SearchRequest, Distance, VectorParams

client = QdrantClient(
    url="127.0.0.1",
    port=6333,
)

try:
    client.create_collection(
        collection_name="xyz",
        vectors_config=VectorParams(size = 512, distance=Distance.COSINE)
    )
except Exception as e:
    print("Collection already exists")
    print(e) # -> prints b'{"status":{"error":"Wrong input: Collection `xyz` already exists!"},"time":0.000045855}'
finally:
    collection = client.get_collection("xyz")
```

the last line `collection = client.get_collection("xyz")` throws this error:

https://pastebin.com/UwGsmijW

```py
File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\qdrant_client\http\api_client.py", line 74, in request
    return self.send(request, type_)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\qdrant_client\http\api_client.py", line 97, in send
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: 1 validation error for ParsingModel[InlineResponse2005] (for parse_as_type)
obj.result.config.optimizer_config.max_optimization_threads 
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/int_type
```

So the error is from this line in qdrant_cleint/http/api_client.py -> class ApiClient.send():

```py
    def send(self, request: Request, type_: Type[T]) -> T:
        response = self.middleware(request, self.send_inner)
        if response.status_code in [200, 201, 202]:
            try:
                return parse_as_type(response.json(), type_) #this line throws the error
            except ValidationError as e:
                raise ResponseHandlingException(e)
        raise UnexpectedResponse.for_response(response)
```

I tried debugging using print statements but i am too unfamiliar with the code base to fix this myself.

The extra weird thing is, that this code has worked before (like 1 month ago) before upgrading to a newer qdrant or pydantic version. However i dont know the previous version in which it worked.

**Comment by generall** [comment]
Hey @MixoMax, please make sure that minor version of the client matches minor version of the server

**Comment by MixoMax** [comment]
that could be the problem:

server: Version: 1.8.3, build: acb04d5f
client: 1.8.0

when i run `pip install qdrant-client==1.8.3` i get:

`ERROR: Could not find a version that satisfies the requirement qdrant-client==1.8.3 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.7, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0)
ERROR: No matching distribution found for qdrant-client==1.8.3`

python version 3.10.11, newest version of pip
I also tried for python version 3.12.2 but that could anso not find qdrant-client==1.8.3.

so how do i either upgrade my qdrant client version to 1.8.3 or downgrade the qdrant server running in docker (`docker pull qdrant/qdrant && docker run -p 6333:6333 qdrant/qdrant`)

**Comment by joein** [comment]
Hi @MixoMax 

There is no `qdrant-client==1.8.3`, qdrant version `1.8.x` should be used with qdrant-client `1.8.x`, as of now qdrant-client latest is `1.8.0`.

I tried to reproduce the issue

I was using python3.10.7

Here is my `pip3 freeze` output:

```
annotated-types==0.6.0
anyio==4.3.0
certifi==2024.2.2
exceptiongroup==1.2.0
grpcio==1.62.1
grpcio-tools==1.62.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.4
httpx==0.27.0
hyperframe==6.0.1
idna==3.6
numpy==1.26.4
portalocker==2.8.2
protobuf==4.25.3
pydantic==2.6.4
pydantic_core==2.16.3
qdrant-client==1.8.0
sniffio==1.3.1
typing_extensions==4.10.0
urllib3==2.2.1
```

I launched qdrant as 
```
docker run -it -p 6333:6333 -p 6334:6334 -e QDRANT__CLUSTER__ENABLED=true --name qdrant qdrant/qdrant:latest ./qdrant --uri "http://localhost:6335"
```

However, the code snippet you provided worked without an exception from pydantic

I ran it 2 times
First time it just created the collection
The second time I had the following output:

```
Collection already exists
Unexpected Response: 409 (Conflict)
Raw response content:
b'{"status":{"error":"Wrong input: Collection `xyz` already exists!"},"time":0.007603988}'
```

We've seen the error you encounters, it happened when qdrant-client was 1.7.x
Could you double-check if you are using the correct interpreter? And if you are using a virtualenv, then could you please check that it is enabled and you are actually activated the correct venv?

**Comment by MixoMax** [comment]
I fixed it by downgrading the server version to 1.8.0 by using `docker run qdrant/qdrant:v1.8.0` instead of running `qdrant/qdrant:latest`
