### ISSUE TITLE
Read consistency setting doesn't work with batch search

### ISSUE THREAD

**Issue by Apmats** [qdrant/qdrant-client#590]
There's a bug when trying to specify read consistency type to do batch search with.

Passing a variable of type `ReadConsistencyType` as an argument to https://github.com/qdrant/qdrant-client/blob/8e3ea58f781e4110d11c0a6985b5e6bb66b85d33/qdrant_client/qdrant_remote.py#L348 fails because this check https://github.com/qdrant/qdrant-client/blob/8e3ea58f781e4110d11c0a6985b5e6bb66b85d33/qdrant_client/qdrant_remote.py#L366 is wrong ( `ReadConsistencyType` doesn't have types as it's arguments).

Instead here we need to check as elsewhere in the file eg. https://github.com/qdrant/qdrant-client/blob/8e3ea58f781e4110d11c0a6985b5e6bb66b85d33/qdrant_client/qdrant_remote.py#L456 if the passed argument is an instance of the type arguments of `ReadConsistency`.

Fix is simple and it's here: https://github.com/qdrant/qdrant-client/pull/589

**Comment by joein** [comment]
Available as of `qdrant-client==1.9.0`
