### ISSUE TITLE
`DATETIME` is not converted from REST to gRPC

### ISSUE THREAD

**Issue by Vasniktel** [qdrant/qdrant-client#604]
The following code doesn't handle the `DATETIME` type. https://github.com/qdrant/qdrant-client/blob/8e3ea58f781e4110d11c0a6985b5e6bb66b85d33/qdrant_client/conversions/conversion.py#L1563-L1576

**Comment by joein** [comment]
Hey @Vasniktel 

Thank for pointing it out, we'll fix it soon

**Comment by joein** [comment]
#605

**Comment by joein** [comment]
Available as of `qdrant-client==1.9.0`
