### ISSUE TITLE
healthz return raw str, but decode use .json()

### ISSUE THREAD

**Issue by 1120475708** [qdrant/qdrant-client#625]
```
    def send(self, request: Request, type_: Type[T]) -> T:
        response = self.middleware(request, self.send_inner)
        if response.status_code in [200, 201, 202]:
            try:
                return parse_as_type(response.json(), type_)
            except ValidationError as e:
                raise ResponseHandlingException(e)
        raise UnexpectedResponse.for_response(response)
```

When I try to call the method client.http.service_api.healthz(), I find the return value is "healthz check passed", but the api uses resp.json() which causes a crash!

**Comment by joein** [comment]
hi @1120475708 

We are not exposing service api methods into the client api, they are currently meant to be invoked with curl / wget / etc

**Comment by 1120475708** [comment]
Alright, I appreciate your response. @joein
