### ISSUE TITLE
Unable to use metadata filter values containing spaces

### ISSUE THREAD

**Issue by ms130** [qdrant/qdrant-client#631]
I'm using the Qdrant document store with Haystack, and would like to apply a metadata filter inside a query pipeline. This works fine when meatadata values don't contain any white spaces, however breaks when they do. With spaces, `parse_json_path()` raises a `ValueError: Invalid path`, see code [here](https://github.com/qdrant/qdrant-client/blob/master/qdrant_client/local/json_path_parser.py#L22-L62).

In my case, metadata values with spaces occurs because I have predicted category labels for documents that sometimes are more than a single word.

It appears `parse_json_path()` only accepts json paths with dot notation, and not also bracket notation. I believe if it were made more flexible to also accept json paths using bracket notation, providing a path with keys containing spaces would not raise an error.

This change would be very useful and make the Qdrant more versatile in handling more varied metadata values as filters.

**Comment by joein** [comment]
Hi @ms130, indeed, this functionality is not currently supported in qdrant.

Btw, it seems like you're using qdrant in local mode. 
Local mode mimics the behaviour of the server (e.g. qdrant in docker).
We'll add it to the local mode as soon as we add it to the server.

@generall @xzfc

**Comment by xzfc** [comment]
Quoted field names are supported, e.g. to match `{"a b": {"c d": "x"}}`, use this:

```python
models.FieldCondition(key='"a b"."c d"', match=models.MatchValue(value="x"))
```

**Comment by ms130** [comment]
Great, thanks it works if I use that formatting. Not sure if it's already mentioned in the docs, but would be helpful to mention this as the way to use field names containing spaces.
