### ISSUE TITLE
Extra inputs are not permitted

### ISSUE THREAD

**Issue by zopidev** [qdrant/qdrant-client#648]
I run search qdrant as in example:

 results = client.search(
        collection_name="amazon",
        query_vector=query_embedding,
        # with_payload=False,
        limit=5,
    )
    
But I got the error:

Traceback (most recent call last):
  File "/app/research-qdrant/path/to/venv/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 88, in send
    return parse_as_type(response.json(), type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/research-qdrant/path/to/venv/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 201, in parse_as_type
    return model_type(obj=obj).obj
           ^^^^^^^^^^^^^^^^^^^
  File "/app/research-qdrant/path/to/venv/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 5 validation errors for ParsingModel[InlineResponse20014] (for parse_as_type)
obj.result.0.order_value
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
obj.result.1.order_value
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
obj.result.2.order_value
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
obj.result.3.order_value
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden
obj.result.4.order_value
  Extra inputs are not permitted [type=extra_forbidden, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden

**Comment by joein** [comment]
hi @zopidev 

could you please tell us the versions of qdrant and qdrant-client you're using?

**Comment by zopidev** [comment]
<img width="278" alt="image" src="https://github.com/qdrant/qdrant-client/assets/156647152/149624ea-0495-4865-acc4-bc2a1b755d5f">
I used command to install :  pip install qdrant-client

**Comment by zopidev** [comment]
Thanks @joein , I upgraded qdrant-client to version 1.9.1 and it worked !!!

**Comment by giacomobartoli** [comment]
Same error for me. I had to upgrade from 1.7.2 to 1.9.2. Thanks for help @joein
