### ISSUE TITLE
Missing Example for Using ColBERT with Python Client in Blog and Documentation

### ISSUE THREAD

**Issue by harsh-sprinklr** [qdrant/qdrant-client#675]
Thank you for the recent updates in Qdrant 1.10. I was reading through the [release blog post](https://qdrant.tech/blog/qdrant-1.10.x/) and noticed that there isn't an example demonstrating how to use ColBERT with the Python client. Could you please confirm if this functionality is supported? If so, could you provide an example or update the documentation accordingly?

Thank you for your assistance.

**Comment by generall** [comment]
![image](https://github.com/qdrant/qdrant-client/assets/1935623/aced088f-001f-4389-adfc-0b3fc40cf750)
https://qdrant.tech/documentation/concepts/vectors/#multivectors
