### ISSUE TITLE
query_points is not working

### ISSUE THREAD

**Issue by projectsenmasa** [qdrant/qdrant-client#716]
Hi, I'm following a tutorial about "How to Build the Ultimate Hybrid Search with Qdrant" (https://www.youtube.com/watch?v=LAZOxqzceEU). I'm following the exact same process that written in this notebook: https://github.com/qdrant/workshop-ultimate-hybrid-search/tree/main/notebooks

My qdrant_client version is already 1.10

I could store the data into my collection, but when I want to retrieve it using query_points, I always get this error message 

```
client.query_points(
    "testing",
    query=next(dense_embedding_model.query_embed(query_text)),
    using="all-MiniLM-L6-v2",
    limit=10,
    with_payload=False,
)
```

![image](https://github.com/user-attachments/assets/b10ccbe5-79f6-4270-8f49-17eb1498bc03)

when I'm using search it shown another error like this:

```
client.search(
    collection_name = "testing",
    query_vector= openai_client.embeddings.create(input=[query_text],
                                                  model=embedding_model).data[0].embedding,
    limit=10,
)
```
![image](https://github.com/user-attachments/assets/4bdaad1f-2a73-4e3a-b01d-13f427dd345b)

It stated that vector params are not specified, but actually I've already specified it ( since I'm just reproducing the exact same notebook provided by Qdrant that I attached above). I've also checked, and here's a detail info from Qdrant UI

![image](https://github.com/user-attachments/assets/9717f02f-fb57-446d-864f-789e536b342d)

If I check with:
`client.get_collection("testing")`

I've also got a detail info that indicates I've already set up the vector params
![image](https://github.com/user-attachments/assets/96cda570-9e43-4041-b739-f79bd686de02)

What's the solution for this? Thanks

**Comment by projectsenmasa** [comment]
hey, I'm not using docker qdrant, I connect it using qdrant cloud like this:

```
from qdrant_client import QdrantClient

client = QdrantClient(
    "https://435610d4-ba1b-4245-5b04-eda945a2e4c9.us-east4-0.gcp.cloud.qdrant.io:6333/",
    api_key= qdrant_api,
)
```

**Comment by hh-space-invader** [comment]
For the search, you should specify the vector name. In your case, for example:
```
query_vector = openai_client.embeddings.create(input=[query_text], model=embedding_model).data[0].embedding
search_result = client.search(
    collection_name="testing",
    query_vector= models.NamedVector(
        name="all-MiniLM-L6-v2", # specify the vector name here
        vector=query_vector 
    ),
    limit=10,
)
```

**Comment by projectsenmasa** [comment]
Thank you for the solution, it's working now for the search! Could you please help me with the query_points problem?

**Comment by hh-space-invader** [comment]
@projectsenmasa Please check qdrant version in cloud ui. It should be > 1.10 for the query_points to work

**Comment by projectsenmasa** [comment]
oh yeah got it, I've checked and found the version here stated that it's still 1.9.2. Is there a way to update this qdrant version in the cloud?
![image](https://github.com/user-attachments/assets/d33c56dc-c6e0-4d3c-852f-6ad9e86f0436)

**Comment by projectsenmasa** [comment]
thank you for the answer, I'll check

**Comment by kunalchamoli** [comment]
I recently migrated my old collection from Qdrant version 1.8.0 to 1.12.0 to enable multitenancy. The migration was done point by point. However, now when I perform a hybrid search on the updated collection, I encounter the same error.
