### ISSUE TITLE
How this BaseModel works?

### ISSUE THREAD

**Issue by 0xSynapse** [qdrant/qdrant-client#733]
I am doing research with recommendation systems, and I found that I can use Qdrant sparse vectors. There I got I need to call the BaseModel in main.py , and I tried to investigate and saw it pulling from pydentic.

But I am not able to understand what the base model is under the hood. Is it a deep learning model like BERT or an algorithm that generates spare vector embeddings from our data?

Am I missing something?

**Can anyone from the team explain the architecture and functionality of the BaseModel !?**

Thank you.

**Comment by generall** [comment]
`BaseModel` is not related to machine learning, it is a base class for data modelling. 

https://docs.pydantic.dev/latest/api/base_model/

**Comment by 0xSynapse** [comment]
@generall then how in code we are generating the sparse vector embeddings, is there any deep learning model working under the hood

```
# Convert ratings to sparse vectors

from collections import defaultdict

user_sparse_vectors = defaultdict(lambda: {
    "values": [],
    "indices": []
})

for row in ratings.itertuples():
    user_sparse_vectors[row.userId]["values"].append(row.rating)
    user_sparse_vectors[row.userId]["indices"].append(row.movieId)
   
```

And what is the use of model class here, is it just doing data processing?

```
# Create collection with configured sparse vectors
# Sparse vectors don't require to specify dimension, because it's extracted from the data automatically

qdrant.create_collection(
    "movielens",
    vectors_config={},
    sparse_vectors_config={
        "ratings": models.SparseVectorParams()
    }
)

```

**Comment by generall** [comment]
please read the tutorial https://qdrant.tech/documentation/tutorials/search-beginners/
