### ISSUE TITLE
Slow batch upload of embeddings generated by fastembed due to `Iterable[ndarray]` conversion to `list[list[float]]`

### ISSUE THREAD

**Issue by vemonet** [qdrant/qdrant-client#776]
Hi, I am using Qdrant and fastembed to index a few text documents (700) and I am finding the  runtime to upload documents really slow. We implemented it following Qdrant official [documentation for batch upload](https://qdrant.tech/documentation/concepts/points/#upload-points). We are running Qdrant as a service in a docker container separated from where the python code doing embeddings runs.

We are generating the embeddings for all documents using fastembed `BAAI/bge-large-en-v1.5` model (1024 dimensions), it is really fast.

But pushing the embeddings to Qdrant itself takes about 5min on my laptop, and approximately the same time on the server

We figured out that the bottleneck comes from **converting the `Iterable[ndarray]` returned by fastembed `.embed()` method** to a list of list of floats, which is required to send the embeddings to the Qdrant API. And it seems to be what the Qdrant python client is doing. 

Here is some code to reproduce the problem using sentences taken from the book Alice in wonderland:

```python
import random
import time
import re
import requests
from fastembed import TextEmbedding
from qdrant_client import QdrantClient, models
from qdrant_client.http.models import Distance, VectorParams

embedding_model = TextEmbedding("BAAI/bge-large-en-v1.5")
vectordb = QdrantClient(location=":memory:")
# Or if running with docker: vectordb = QdrantClient(host="vectordb", prefer_grpc=True)
vectordb.recreate_collection(
    collection_name="mycollection",
    vectors_config=VectorParams(size=1024, distance=Distance.COSINE),
)

# Get 700 sentences from the Alice in wonderland book
text = requests.get("https://www.gutenberg.org/files/11/11-0.txt").text
docs = re.split(r'(?<=[.!?]) +', text)
# Filter out short or empty sentences and take 700 first sentences
docs = [sentence.strip() for sentence in docs if len(sentence.split()) > 5]
docs = docs[8:708]
print(docs[:5])

# Or generate 700 random sentences with no real semantic meaning
# docs = set()
# while len(docs) < 700:
#     length = random.randint(5, 15)
#     sentence = " ".join(random.choices(["the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog", "in", "the", "forest", "under", "sunlight", "swiftly", "runs", "towards", "adventure"], k=length))
#     docs.add(sentence)

embeddings = embedding_model.embed(docs)
print(f"Done generating embeddings for {len(docs)} documents")
start_time = time.time()
embed_list = [embedding.tolist() for embedding in embeddings]
print(f"This prints after a way too long time: {time.time() - start_time} seconds")
vectordb.upsert(
    collection_name="mycollection",
    points=models.Batch(
        ids=list(range(1, len(docs) + 1)),
        # vectors=embeddings, # Passing the Iterable[ndarray] directly takes as much time as doing conversion to a list ourself
        vectors=embed_list,
        payloads=[{"doc_type": "random", "index": i} for i in range(len(docs))],
    ),
)
print(f"Done inserting and indexing {len(docs)} documents in {time.time() - start_time} seconds")
```

If you change the code to uncomment the `vectors=embeddings` part and comment the ndarray conversion part, you can see that manually converting the `Iterable[ndarray]` to a list of list of float, ends up taking exactly as much time as when passing the list of `Iterable[ndarray]` directly to the Qdrant client (~300s on my laptop on CPU). And the indexing process itself only takes 0.1s!

So I guess the python `qdrant_client` is also doing the conversion from `Iterable[ndarray]` to list using something like `.tolist()` in python before sending it to the API.

> I also noticed that when doing the same thing with embeddings from 700 sentences randomly generated the `[embedding.tolist() for embedding in embeddings]` bit is only taking 12s... (even if its all done on lists of floats of the same size, I guess there are some "optimizations" in numpy that are triggered by the fact we reused the same words when generating the sentences)

What would be the best solution to increase performance when sending multiple embeddings generated by fastembed to Qdrant in python? I see a few solutions, but not sure which one would be best, and maybe the Qdrant team has already a good solution (I am probably not the first person having this problem since it comes directly from following the official docs for batch upload, and we are not even working with really large batch):

* Maybe there is a faster solution to convert `Iterable[ndarray]` to a list of lists of float in python? In this case ideally this should be directly integrated to the `qdrant_client` python library
* fastembed could provide a  `.embed()` function that directly returns the embeddings as lists. So this would be done quickly directly in rust and we wouldn't need to do it so slowly with numpy in python 

Thanks a lot!

**Comment by joein** [comment]
hi @vemonet 

`embed` function returns a generator, which is a lazy structure
inference does not happen until you iterate over the generator
so I would say that the slow part here is inference itself, rather than qdrant-client and its conversions
