### ISSUE TITLE
Support: Multi-channel search？？？

### ISSUE THREAD

**Issue by SevenMpp** [qdrant/qdrant-client#783]
There are many kinds of data. 
1、If we put them into a collection, how can we search them at the same time? The expected result is to get the top K of each kind of data.
2、If they are placed in different collections, is it possible to search for multiple items at the same time?

**Comment by joein** [comment]
Hi @SevenMpp 
1. If you have vectors for data objects of several modalities (e.g. text (for instance product description) and image), you can use `query_points` methods to do queries with both vectors and then rescore them e.g. using RRF
It is might be treated as a [hybrid search case](https://qdrant.tech/documentation/concepts/hybrid-queries/#hybrid-search)
2. No, you can't search across several collections with one request
