### ISSUE TITLE
QdrantFastembedMixin.set_sparse_model() does not support 'local_files_only' param

### ISSUE THREAD

**Issue by mjezequel** [qdrant/qdrant-client#793]
fastembed embeddings support local models thanks to parameter 'local_files_only' since https://github.com/qdrant/fastembed/pull/223 
This is well managed by QdrantFastembedMixin.set_model(), but not by QdrantFastembedMixin.set_sparse_model()

qdrant_client.set_model("sentence-transformers/paraphrase-multilingual-mpnet-base-v2", local_files_only=True, cache_dir="/my/cache")  is ok
qdrant_client.set_sparse_model("'Qdrant/bm25'", local_files_only=True, cache_dir="/my/cache") throw an exception: 
TypeError: QdrantFastembedMixin.set_sparse_model() got an unexpected keyword argument 'local_files_only'

**Comment by joein** [comment]
Hi @mjezequel 

Could you please provide the versions of qdrant-client and fastembed you are using?

**Comment by joein** [comment]
Hey @mjezequel,
we have fixed it in the latest release, should be working as qdrant-client 1.12.0

feel free to re-open the issue if it still occurs for you
