### ISSUE TITLE
Question about usage of `embed` instead of `query_embed` in `query` method in `QdrantFastembedMixin`

### ISSUE THREAD

**Issue by martinkozle** [qdrant/qdrant-client#796]
https://github.com/qdrant/qdrant-client/blob/e2ad0661037fe40478ca2e3300f2b3c275183b5e/qdrant_client/qdrant_fastembed.py#L698

Hello, I have a question.

For the Fastembed mixin, why is `embed` used for sparse embeddings instead of `query_embed`? From what I read, for bm25 specifically at least, is that it doesn't use term frequency and length, but instead sets a uniform 1.0 for each token. What is the effect of that difference here? Is 'query_embed' for sparse embeddings not meant to be used with Qdrant?

**Comment by joein** [comment]
Hey @martinkozle 

We have fixed it in the latest release (1.12.0), `query` method should now use the correct embed function
