### ISSUE TITLE
async upload points not working properly

### ISSUE THREAD

**Issue by pydv9991** [qdrant/qdrant-client#798]
this is my code using llamaindex==0.10.68 and qdrant client==1.11.3 with use_async= True it gives error without it it works

 self.client = qdrant_client.QdrantClient(
                host=config.qdrant.host,
                port=config.qdrant.port,
                grpc_port=config.qdrant.aport, 
                prefer_grpc=True
                # api_key=os.getenv('SECRET_KEY') 
            )
            self.aclient = qdrant_client.AsyncQdrantClient(
                host=config.qdrant.host,
                port=config.qdrant.port,
                grpc_port=config.qdrant.aport, 
                prefer_grpc=True
                # api_key=os.getenv('SECRET_KEY') 
            )
            # print(self.aclient)
            vector_store = QdrantVectorStore(
                        config.qdrant.collection,
                        client=self.client,
                        aclient=self.aclient,
                        prefer_grpc=True,
                        enable_hybrid=True,
                        fastembed_sparse_model=config.qdrant.fastembed_sparse_model,
                        batch_size = 64,
                    )

            self.rag_object = VectorStoreIndex.from_vector_store(
                vector_store=vector_store,
                use_async = True,
                show_progress = True,
                quantization_config = models.ScalarQuantization(
                                scalar=models.ScalarQuantizationConfig(
                                    type=models.ScalarType.INT8,
                                    always_ram=True,
                                ),
                            ),
                optimizers_config=models.OptimizersConfigDiff(default_segment_number=16),
                hnsw_config=models.HnswConfigDiff(on_disk=False),
            )
and then this is how i am calling add nodes
self.rag_object._async_add_nodes_to_index(self.rag_object.index_struct, docs, show_progress=True)

getting this error not able to resolve it.
in async_add
    await self._aclient.upload_points(
TypeError: object NoneType can't be used in 'await' expression

**Comment by joein** [comment]
@Anush008  could you please take a look?
It seems that `self._aclient` was not initialized (or something similar happened)

**Comment by pydv9991** [comment]
hi @joein it is initialized i have debugged it both clients are initialize.
with use_async = True it gives error without is it works.

**Comment by Anush008** [comment]
Please update the `llama-index-vector-stores-qdrant` package to latest. i.e. `0.3.0`.

**Comment by Anush008** [comment]
This looks like a different error though.

**Comment by Anush008** [comment]
Awesome!

**Comment by pydv9991** [comment]
@Anush008 @joein one thing more using _async_add_nodes_to_index(self.rag_object.index_struct, docs, show_progress=True) all nodes are processed sequentially what can i do to process all nodes in parallel?

**Comment by Anush008** [comment]
I don't see a pre-built way of doing so.

You'll probably have to split and parallelize the task externally.

**Comment by pydv9991** [comment]
@Anush008 https://github.com/run-llama/llama_index/issues/14238
