### ISSUE TITLE
Vector values are changed

### ISSUE THREAD

**Issue by kimx3966** [qdrant/qdrant-client#822]
I inserted a vector with all values set to 1 into the vector database. When I retrieved it through a search, all metadata was identical, but the vector values had changed from 1 to 0.0069877123. Could there be an issue?

    vectordb_client.upsert(
            collection_name,
            points=[
                models.PointStruct(
                    id=pid,
                    vector=np.ones(shape=(feat_dim,), dtype=np.int8),
                    payload={"gender": "unknown", "race": "unknown", "image_number": -1,
                )
            ]
        )

    uncond_feat_point = vectordb_client.query_points(
        collection_name=collection_name,
        query=np.ones(shape=(feat_dim,), dtype=np.int8),
        query_filter=models.Filter(
            must=[
                models.FieldCondition(
                    key="gender",
                    match=models.MatchValue(value="unknown"),
                )
            ]
        ),
        with_vectors=True,
        with_payload=True,
    )

print(uncond_feat_point.points[0].vector)
=> ..., 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123, 0.0069877123]

**Comment by joein** [comment]
hi @kimx3966 

could you show us how did you create your collection?

**Comment by joein** [comment]
Did you specify `datatype=models.Datatype.UINT8` in collection creation?

**Comment by kimx3966** [comment]
When I used the COSINE metric in vectors_config, the vector values changed. However, when I used the DOT metric, the vector values did not change. Does this mean the vector values are being normalized when using the COSINE metric?


vectordb_client.create_collection(
    collection_name,
    vectors_config=models.VectorParams(
        size=feat_dim,
        **distance=models.Distance.COSINE, # -> models.Distance.DOT**
        datatype=models.Datatype.FLOAT32,
    )
)

**Comment by joein** [comment]
yes, with cosine vectors values being normalized

**Comment by kimx3966** [comment]
Ok, I got it. Thanks
