### ISSUE TITLE
expose settings for channel-level compression

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-client#87]
related reference https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/examples/python/compression/

**Comment by avirlrma** [comment]
Where would we want to expose this setting - at the client level or at per method level?

**Comment by joein** [comment]
At the client

**Comment by Merthoshan** [comment]
Can I get a little more detail as to what the problem is? I would like to work on it

**Comment by joein** [comment]
implemented in #480
